### ISSUE TITLE
v0.11 - when using `--progress plain` the stderr is outputted only at the end of the run.

### ISSUE THREAD

**Issue by j-martin** [dagger/dagger#7077] opened 2024-04-10 17:37 UTC
### What is the issue?

Hey there, 

After upgrading to v0.11, I noticed that when using `--progress plain`, the stderr is outputted only at the end of the run. Why is this important? When running in CI, there will be no feedback given to the user (unless the go code explicitly writes to stdout/err) until the end of the run. This may take minutes.

That being said, the new `plain` output, once it has been outputted, is SOOOOO MUCH better in v0.11. 🙂 

Expected: the dagger/container/services stderr is streamed as it generated like in <= 0.10

Actual Behaviour: the dagger/container/services stderr dumped at the end of the run.

I believe it is a regression from dagger v0.10.X. Using `--progress tty` "fixes" the issue, but the output is not suitable for a standard CI.

You can find an example here: https://github.com/j-martin/dagger-mysql/tree/f8fbe224264f7fc0bf48730dccb0a5e4a1039124

### Dagger version

dagger v0.11.0 (registry.dagger.io/engine) darwin/arm64

### Steps to reproduce

1. Checkout code in https://github.com/j-martin/dagger-mysql/tree/f8fbe224264f7fc0bf48730dccb0a5e4a1039124
2. Run `dagger run --progress plain go run ./main.go`

### Log output

delayed logs, but the same logs

**Comment by helderco** [comment] 2024-04-10 22:54
Duplicate of https://github.com/dagger/dagger/issues/7057

**Closed** 2024-04-10 22:54 UTC
