### ISSUE TITLE
✨ Allow to invalidate cache for a complete pipeline or a step via the SDK

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#3626] opened 2022-11-01 15:27 UTC
### What are you trying to do?

Force the pipeline to re-run some steps that would be cached otherwise.

### Why is this important to you?

Because dagger/buildkit has an opinionated way of caching that sometimes I want to override for specific tasks.

### How are you currently working around this?

Removing the buildkit container and volume which is not idea..

**Comment by sipsma** [comment] 2022-11-01 18:59
Dupe of https://github.com/dagger/dagger/issues/3073

**Closed by sipsma** 2022-11-01 18:59 UTC
Labels: kind/enhancement, area/core, area/sdk
