### ISSUE TITLE
🐞 Function fails when argument is named `json`

### ISSUE THREAD

**Issue by staticaland** [dagger/dagger#6858] opened 2024-03-08 10:56 UTC
### What is the issue?

When attempting to execute a function that includes an argument named `json`, I encounter an error, despite anticipating it would function correctly.

This issue arises in the context of developing a Dagger function for [cloc](https://github.com/AlDanial/cloc). Given that the command-line interface offers options such as `--json` and `--yaml`, I aimed to directly correlate these with a boolean parameter in the Dagger function.

### Dagger version

dagger v0.10.1 ([registry.dagger.io/engine](http://registry.dagger.io/engine)) darwin/arm64

### Steps to reproduce

Run this function with `dagger call cloc-dir --directory-arg='.'`:

```go
type Cloc struct{}
 
// Count lines of code in a directory
func (m *Cloc) ClocDir(
 ctx context.Context,
 directoryArg *Directory,
 // json output
 // +optional
 json bool,
 // yaml output
 // +optional
 yaml bool,
) (string, error) {
 command := []string{"cloc", "--quiet", "--hide-rate"}
 
 if json {
  command = append(command, "--json")
 }
 
 if yaml {
  command = append(command, "--yaml")
 }
 
 command = append(command, ".")
 
 return dag.Container().
  From("alpine:latest").
  WithExec([]string{"apk", "add", "cloc"}).
  WithMountedDirectory("/mnt", directoryArg).
  WithWorkdir("/mnt").
  WithExec(command).
  Stdout(ctx)
}
```

### Log output

Error message:

```
json.Unmarshal undefined (type bool has no field or method Unmarshal)
```

Full output:

```
          ﻿﻿✘ initialize 0.5s
  ✔ ModuleSource.asModule: Module! 0.2s
  ✘ Module.initialize: Module! 0.2s
    ✘ exec go build -o /runtime . 0.2s
    ┃ # dagger/cloc
    ┃ ./dagger.gen.go:597:16: json.Unmarshal undefined (type bool has no field or method Unmarshal)
    ┃ ./dagger.gen.go:604:16: json.Unmarshal undefined (type bool has no field or method Unmarshal)
Error: input: module.withSource.initialize failed to initialize module: failed to call module "cloc" to get functions: call constructor: process "go build -o /runtime ." did not complete successfully: exit code: 1
 
Stderr:
# dagger/cloc
./dagger.gen.go:597:16: json.Unmarshal undefined (type bool has no field or method Unmarshal)
./dagger.gen.go:604:16: json.Unmarshal undefined (type bool has no field or method Unmarshal)
```

**Comment by jedevc** [comment] 2024-03-08 11:22
Linking this to https://github.com/dagger/dagger/issues/6186, this is a more specific form of that issue.

**Comment by helderco** [comment] 2024-07-06 14:13
Duplicate of https://github.com/dagger/dagger/issues/7032

Closing this one even though created first, because the other is more generic and has an ongoing discussion.

**Closed by helderco** 2024-07-06 14:13 UTC
