### ISSUE TITLE
Generated gitattributes should be generated in module source, not module root 

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#6654] opened 2024-02-13 10:51 UTC
If I have a module with a `source` key set to a `./ci`, when I run `dagger develop`, I expect that the generated `.gitattributes` file should be generated into `./ci`, and not at the top-level where my `dagger.json` is.

Alternatively, if we do decide that the top-level *is* the right place to put it, then the file should contain the right paths. Today, it looks something like:

```
/dagger.gen.go linguist-generated
/querybuilder/** linguist-generated
```

Even though `dagger.gen.go` and `querybuilder` are not in `/`, but in `/ci`.

**Comment by helderco** [comment] 2024-02-13 11:00
Duplicate of #6625

**Closed** 2024-02-13 11:08 UTC
