### ISSUE TITLE
📖 Implement `BUILDKIT_CA_CERTS` env variable to mount CA certificates inside spawned `dagger-buildkitd` container

### ISSUE THREAD

**Issue by qjcg** [dagger/dagger#2016] opened 2022-04-04 11:22 UTC
### What is the issue?

I'm trying to push an image to our private registry, but `docker.#Push` is failing with `x509: certificate signed by unknown authority`.

I'm running `dagger` locally on macOS and can confirm that the our private CA cert **is indeed present** in the system keychain as described [here](https://docs.docker.com/desktop/mac/#add-custom-ca-certificates-server-side). I am able to manually run `docker push my.private.registry/proj/example` without issue.

### Log output

```console
[✗] actions.push               0.2s
6:15AM FTL failed to execute plan: task failed: actions.push._push: failed to do request: Head "https://<... redacted ...>/blobs/sha256:36d215df336793e88ec6c4e3b7ac55c1b553b65541854a0ce1b2171970ae9ede": x509: certificate signed by unknown authority
```

### Steps to reproduce

1. Use `docker.#Push & { dest: "my.private.registry/proj/example" }` in a dagger action, where the `my.private.registry` server certificate is signed by a private trusted CA.

### Dagger version

0.2.4

### OS version

macOS 10.15.7

**Comment by helderco** [comment] 2022-04-04 11:27
Are you actually using `$private-registry` in there, or is it just a placeholder for the example?

**Comment by qjcg** [comment] 2022-04-04 11:27
> Are you actually using `$private-registry` in there, or is it just a placeholder for the example?

Just a placeholder for the example :)

**Comment by helderco** [comment] 2022-04-04 11:29
Ok, but just to be clear... you're **not** trying to expand an environment variable inside `dest`?

**Comment by qjcg** [comment] 2022-04-04 11:32
> you're **not** trying to expand an environment variable inside `dest`?

No, not trying to expand any environment variables in side dest or anywhere else.

**Comment by helderco** [comment] 2022-04-04 11:52
Ok, I've used it successfully with the `registry:2` docker image, behind Nginx and Let's Encrypt (in docker Swarm).

Can you give any more details about your setup to enable us to reproduce your issue?

**Comment by grouville** [comment] 2022-04-04 12:40
@helderco related I think: https://github.com/dagger/dagger/issues/2016

**Comment by grouville** [comment] 2022-04-04 12:57
@qjcg I think there are two possibilities: you try to mount this certificate inside the container and check is it works (🤞), or you'll need to have a custom Buidlkit setup if the certificate needs to be inside the buildkit container. An example is present here, and we can totally help: https://github.com/tonistiigi/buildkit/blob/56f76a56211bee437c0ef78e8fd9314bf9da9639/docs/buildkitd.toml.md

How to connect to this different container:
https://github.com/dagger/dagger/blob/3ddf6c995c09d172ba1280939f2c16ea48316b9a/docs/administrator/1013-operator-manual.md

**Comment by qjcg** [comment] 2022-04-04 13:18
> self-signing or using a CA we don't have included

Yes, I confirm that this is the case.

> you'll need to have a custom Buildlkit setup if the certificate needs to be inside the buildkit container

After some more review, I'm pretty confident this is what will be needed, since from what I understand, `docker.#Pull` is executed in the buildkit container.

I'll work on creating and using a [custom buildkit](https://github.com/dagger/dagger/blob/3ddf6c995c09d172ba1280939f2c16ea48316b9a/docs/administrator/1013-operator-manual.md) (thanks for this link @grouville !) and report back here.

**Comment by grouville** [comment] 2022-04-04 13:26
> iew, I'm pretty confident this is what will be needed, since from what I understand, `docker.#Pull` is executed in the buildkit container.

You may try this:
```
docker run --net=host -d --restart always -v <mount you certificate> --name dagger-buildkitd --privileged moby/buildkit:v0.10.0
```

**Comment by qjcg** [comment] 2022-04-04 18:32
`docker run --net=host -d --restart always -v $PWD/my-cert.pem:/etc/ssl/certs/my-cert.pem --name dagger-buildkitd --privileged moby/buildkit:v0.10.0`

@grouville I can confirm that running the above, mounting our private CA cert into the buildkit container, DOES in fact fix the issue --- I was able to use `docker.#Push` successfully in my dagger pipeline. Thank you!

My 2 cents: this seems like a common enough scenario that a standard, built-in way to do this would take this from "fiddly & manual" UX to "awesome" UX :)

Maybe something like:

```cue
dagger.#Plan & {
  client: buildkit: certs: ca: [
    "myCA1.pem",
    "myCA2.pem",
  ]
  ...
}
```

**Comment by grouville** [comment] 2022-04-04 20:01
> > `docker run --net=host -d --restart always -v $PWD/my-cert.pem:/etc/ssl/certs/my-cert.pem --name dagger-buildkitd --privileged moby/buildkit:v0.10.0`
> 
> @grouville I can confirm that running the above, mounting our private CA cert into the buildkit container, DOES in fact fix the issue --- I was able to use `docker.#Push` successfully in my dagger pipeline. Thank you!
> 
> My 2 cents: this seems like a common enough scenario that a standard, built-in way to do this would take this from "fiddly & manual" UX to "awesome" UX :)
> 
> Maybe something like:
> 
> ```cue
> dagger.#Plan & {
>   client: buildkit: certs: ca: [
>     "myCA1.pem",
>     "myCA2.pem",
>   ]
>   ...
> }
> ```

Excellent idea 😇 
cc @helderco wdyt ?

**Comment by GooseYArd** [comment] 2022-04-04 20:24
I work in an organization which using an image registry which, in addition to presenting a server cert issued by a non-public CA, also requires a client certificate issued by the same CA for access, so ideally the mechanism used to identify the location of the issuing CA could include additional fields for a cert and key if client cert auth is required.

**Comment by helderco** [comment] 2022-04-04 21:16
I don't think it should be in the plan. Using environment variables would be better. Like when you connect to a remote docker daemon you have `DOCKER_TLS_VERIFY` and `DOCKER_CERT_PATH`.

**Comment by qjcg** [comment] 2022-04-05 00:55
Env vars could definitely work, something like BUILDKIT_CA_CERTS.

**Comment by shykes** [comment] 2022-12-21 21:46
I'm closing this since @qjcg fixed their problem with a workaround.

Note that the core issue (ability to configure trusted CAs to support private docker registries) is not yet fixed - workarounds are still needed. Solving that issue is finally moving to the top of our list, and is tracked here: #4217

**Closed by shykes** 2022-12-21 21:46 UTC
Labels: kind/user-request, sdk/cue
