### ISSUE TITLE
🐞 `exec`s not cached after `copy`ing anything from host

### ISSUE THREAD

**Issue by mikeroll** [dagger/dagger#5451] opened 2023-07-14 14:51 UTC
### What is the issue?

Using Python SDK 0.6.3 and running the following code:
```
import dagger, anyio, sys

async def main() -> None:
    config = dagger.Config(log_output=sys.stderr)
    connection = dagger.Connection(config)

    async with connection as client:
        source = client.host().directory(".", include=["testfile"])
        await (
            client.container()
            .from_("busybox")
            .with_file("/testfile", source.file("testfile"))
            .with_exec(["sh", "-c", "sleep 3 && ls -lsa"])
            .stdout()
        )


anyio.run(main)
```
`.with_file()` is cached as expected as the file never changes;
`.with_exec()` is never ever cached and in always executed.

What's especially interesting is that `.with_exec()` is properly cached if `source.file()` comes from another `client.container()` and not `client.host()`.

I do not observe the problem with Python SDK 0.6.2.

### Log output

First run:
```
❯ python ci.py
--snip--
15: copy /testfile /testfile
15: copy /testfile /testfile DONE

13: exec sh -c sleep 3 && echo done
13: [3.15s] done
13: exec sh -c sleep 3 && echo done DONE
```

Second and subsequent runs:
```
❯ python ci.py
--snip--
15: copy /testfile /testfile CACHED
15: copy /testfile /testfile CACHED

13: exec sh -c sleep 3 && echo done
13: [3.15s] done
13: exec sh -c sleep 3 && echo done DONE
```

### SDK version

Python SDK 0.6.3

### OS version

Arch Linux

**Comment by helderco** [comment] 2023-07-14 14:55
Duplicate of #5450

**Closed by helderco** 2023-07-14 14:55 UTC
