### ISSUE TITLE
NodeJS SDK: Check if docker is running

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#3854] opened 2022-11-15 19:45 UTC
If docker isn't running you get the following error:

<img width="1914" alt="Screenshot_2022-11-15_at_11 35 10_AM" src="https://user-images.githubusercontent.com/1186424/202011258-aae0579a-1bac-4845-b3e2-a93b5eea9c16.png">

We should catch this error and display an appropriate message.

**Comment by marcindulak** [comment] 2022-11-15 21:08
A text log is useful for searches. There could be other issues resulting in this error, so a more explanatory message, digging deeper into the source of the error may be needed. 

For example, I'm getting the following, when trying to execute a nodejs example https://github.com/dagger/dagger/pull/3823 with https://www.npmjs.com/package/@dagger.io/dagger/v/0.1.0-alpha.2, from within a container that mounts `/var/run/docker.sock`. At the same time `docker run hello-world` works. Trying to create a reproducible example.

```
Error: Command failed with Unknown system error -8: /home/node/.cache/dagger/dagger-engine-session-666b958a2f716c0d --remote docker-image://ghcr.io/dagger/engine:v0.3.4@sha256:666b958a2f716c0d6b22d869c585d6fe07954133ec769bb3d1f310e931cb118f --workdir /app
spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:743:9)
    at execa (file:///app/node_modules/execa/index.js:84:26)
    at execaCommand (file:///app/node_modules/execa/index.js:229:9)
    at DockerImage.<anonymous> (file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:183:31)
    at Generator.next (<anonymous>)
    at file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:3:12)
    at DockerImage.runEngineSession (file:///app/node_modules/@dagger.io/dagger/dist/provisioning/docker-provision/image.js:175:16) {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn',
  originalMessage: 'spawn Unknown system error -8',
  shortMessage: 'Command failed with Unknown system error -8: /home/node/.cache/dagger/dagger-engine-session-666b958a2f716c0d --remote docker-image://ghcr.io/dagger/engine:v0.3.4@sha256:666b958a2f716c0d6b22d869c585d6fe07954133ec769bb3d1f310e931cb118f --workdir /app\n' +
    'spawn Unknown system error -8',
  command: '/home/node/.cache/dagger/dagger-engine-session-666b958a2f716c0d --remote docker-image://ghcr.io/dagger/engine:v0.3.4@sha256:666b958a2f716c0d6b22d869c585d6fe07954133ec769bb3d1f310e931cb118f --workdir /app',
  escapedCommand: '"/home/node/.cache/dagger/dagger-engine-session-666b958a2f716c0d" --remote "docker-image://ghcr.io/dagger/engine:v0.3.4@sha256:666b958a2f716c0d6b22d869c585d6fe07954133ec769bb3d1f310e931cb118f" --workdir "/app"',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  all: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by sipsma** [comment] 2022-11-15 21:24
@marcindulak that looks like it may be a bug we just fixed in the latest release: https://www.npmjs.com/package/@dagger.io/dagger/v/0.1.0-alpha.3

To fix it locally you will need to run `rm /home/node/.cache/dagger/dagger-engine-session-666b958a2f716c0d`, then that problem shouldn't reappear going forward.

**Comment by marcindulak** [comment] 2022-11-15 22:01
Just submitted https://github.com/dagger/dagger/issues/3857 with a test case - I'm doing this from within a container, so I think a manual intervention is not a solution.

**Comment by sipsma** [comment] 2022-11-15 22:20
> Just submitted https://github.com/dagger/dagger/issues/3857 with a test case - I'm doing this from within a container, so I think a manual intervention is not a solution.

To be clear the manual intervention is a one-time thing, should not be needed going forward. I will get back on your other issue too, thanks for reporting this!

**Closed** 2022-12-12 13:10 UTC
Labels: sdk/nodejs
