### ISSUE TITLE
🐞 tutorial failed using example app

### ISSUE THREAD

**Issue by charlieviolet** [dagger/dagger#2054] opened 2022-04-06 06:51 UTC
### What is the issue?

when tried to do example app command: dagger do build, it reported below errors

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/13729266/161912868-a0798d42-a352-43f1-bc2f-0f713980fca8.png">

### Dagger version

dagger 0.2.5 (7d2f279c) linux/amd64

### OS version

CentOS Linux release 7.2 (Final)

**Comment by d3rp3tt3** [comment] 2023-01-14 21:30
This issue was reported in April for a previous version of Dagger where the CLI included the `dagger do` command. I think it's best to close it unless @charlieviolet has seen this issue reproduced in sample apps in newer versions of Dagger.

The screenshot looks like this is from the ToDo example app. https://github.com/dagger/todoapp

**Comment by slumbering** [comment] 2023-01-16 09:21
> This issue was reported in April for a previous version of Dagger where the CLI included the `dagger do` command. I think it's best to close it unless @charlieviolet has seen this issue reproduced in sample apps in newer versions of Dagger.
> 
> The screenshot looks like this is from the ToDo example app. https://github.com/dagger/todoapp

Correct! Thanks @d3rp3tt3.

**Closed by slumbering** 2023-01-16 09:21 UTC
Labels: area/documentation, kind/user-request
