### ISSUE TITLE
🐞 Dagger engine container is unable to refresh authorization for Google Artifact Registry

### ISSUE THREAD

**Issue by davidwallacejackson** [dagger/dagger#4698] opened 2023-03-04 08:19 UTC
### What is the issue?

I was working on a script with the Go SDK, running it repeatedly to test pushes to a registry, when I suddenly got this error:

```
input:1: container.withDirectory.publish failed to solve: failed to push [PATH REDACTED]: unexpected status from HEAD request to https://[PATH REDACTED]: 401 Unauthorized
       
       Please visit https://dagger.io/help#go for troubleshooting guidance.
```

The time was just after midnight, so I figured some automated process had logged me out or revoked my permissions. I tried a push using the `docker` CLI and found that I was still able to push. On a hunch, I then deleted the docker container for the Dagger engine and re-ran -- at which point my script was able to push again.

### Steps to reproduce

Log into Google Artifact Registry with gcloud, e.g.

```bash
gcloud auth login
gcloud auth configure-docker us-central1-docker.pkg.dev
```

Run a dagger script that `Publish()`s a container to a repository that you have write access to. Then wait until after midnight (not sure if it's local midnight or PST), and run the script again.

### SDK version

Go SDK 0.4.6

### OS version

macOS 12.3.1 (ARM)

**Comment by jpadams** [comment] 2023-03-08 01:05
@sipsma Looks like we're on 
`github.com/moby/buildkit v0.11.0-rc3.0.20230222163458-34a576c411ea` perhaps?

Seems that `v0.11.2` fixed issues related to "pusher" that seem related:
https://github.com/moby/buildkit/releases/tag/v0.11.2
https://github.com/moby/buildkit/pull/3531
https://github.com/containerd/containerd/pull/7990

`containerd` pusher issues with GCR previously:
https://github.com/containerd/containerd/issues/4622#issuecomment-716746004

**Comment by sipsma** [comment] 2023-03-15 18:54
@d3rp3tt3 - David said he's on Go SDK 0.4.6, I just checked and that should have already had the fix in place, so I suspect that commit did not end up fixing the issue for him. I think it's worth it for us to see if we can repro it on our latest commits and if still present fix the problem.

**Comment by mircubed** [comment] 2023-03-15 18:58
Assigning to @grouville to work on reproducing.

**Comment by grouville** [comment] 2023-04-07 15:32
@mircubed

After syncing with @TomChv, and with the fact that I have some bandwidth today. I'm currently doing the repro. Let's check the behavior tomorrow

**Comment by grouville** [comment] 2023-04-10 11:04
I can confirm that this has been resolved. Using this test script: https://gist.github.com/grouville/1cbc9c73926570bcdc4b57cd49cde11c.

My tests consisted of:
1. Logging in with Google Artifact Registry:
```shell
gcloud auth login
gcloud auth configure-docker us-central1-docker.pkg.dev
```
2. The same day:
- Publishing using Docker CLI
  - `docker build -t us-central1-docker.pkg.dev/***/***/jojo:latest .`
  - `docker push us-central1-docker.pkg.dev/***/***/jojo:latest`
- Do the same with above Go SDK
  - `go run .`
  
  Result: ![Image](https://user-images.githubusercontent.com/31691250/230641585-cdfeb2ca-e8d2-4118-bd0e-6f830a39147e.png)
  
3. Do the same after midnight / a following day without authentication using the docker CLI
  
**If it works, then issue has been resolved by bumping the buildkit version.**

Just did it and everything went smoothly ✅ 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/31691250/230889999-5da2ca47-a350-4cf5-9566-61bc08312e24.png">

**Closed by grouville** 2023-04-10 11:04 UTC
Labels: kind/bug, kind/dx, kind/user-request
