### ISSUE TITLE
Documentation link redirects to "Page Not Found"

### ISSUE THREAD

**Issue by kyrylo-merzlikin-blablacar** [dagger/dagger#2863] opened 2022-07-27 10:24 UTC
### What is the issue?

When trying to access Dagger documentation via the [link](https://docs.dagger.io/) on the home page I get redirected to a broken "Page Not Found" page with URL https://docs.dagger.io/restricted.
  
<img width="734" alt="Screenshot 2022-07-27 at 13 20 30" src="https://user-images.githubusercontent.com/92081104/181224723-609e187b-071a-45d0-a1c7-a67c2ce6f84e.png">

This isn't an expected behaviour, is it?

**Comment by jpadams** [comment] 2022-07-27 15:20
Thanks @kyrylo-merzlikin-blablacar .

I can't reproduce your error. Are you still experiencing it?

**Comment by crjm** [comment] 2022-07-27 15:26
The redirection comes from [this line](https://github.com/dagger/dagger/blob/7c0a5e7bfdbcae75a19c16a28c0967b5edb4dd75/website/netlify.toml#L14).

**Comment by jpadams** [comment] 2022-07-27 16:12
@kyrylo-merzlikin-blablacar sorry for this. We're looking into it to see if there is a workaround.

**Comment by slumbering** [comment] 2022-07-27 16:33
@kyrylo-merzlikin-blablacar . Just create a PR #2865 to restrict only Crimea. Not sure Netlify will concider it though.

**Comment by crjm** [comment] 2022-07-27 16:52
Hey @kyrylo-merzlikin-blablacar, can you check if you can enter [this link](https://deploy-preview-2865--devel-docs-dagger-io.netlify.app/)?

**Comment by crjm** [comment] 2022-07-27 21:40
Great! The PR has been merged, you should now be able to visit https://docs.dagger.io

**Comment by crjm** [comment] 2022-07-28 14:13
@kyrylo-merzlikin-blablacar no worries, we are working on it. Thanks for your concern.

**Closed by crjm** 2022-07-28 14:13 UTC
