### ISSUE TITLE
🐞 dagger do build on the example "todoapp" project fails due to incompatible version

### ISSUE THREAD

**Issue by gberl002** [dagger/dagger#2921] opened 2022-08-09 20:41 UTC
### What is the issue?

I installed dagger on my Apple Silicon Mac, cloned the tutorial app "todoapp" per the tutorial's instructions but received an error.

```
dagger do build
ERROR system | failed to load plan: package "dagger.io" is incompatible with this version of dagger (requires 0.2.11 or newer). Run `dagger project update` to resolve this
```

### Log output

ERROR system | failed to load plan: package "dagger.io" is incompatible with this version of dagger (requires 0.2.11 or newer). Run `dagger project update` to resolve this

### Steps to reproduce

1. install the latest dagger using Homebrew (probably doesn't matter regarding the method of install). `brew install dagger/tap/dagger`
2. Clone the tutorial app (per the instructions) `git clone https://github.com/dagger/todoapp`
3. CD into the app root directory `cd todoapp`
4. Try to build the app `dagger do build`

The error was helpul in that `dagger project update` updated the project properly but for ease of use by the end user, the example app should be updated in github.

### Dagger version

dagger 0.2.28 (41b7d6190) darwin/arm64

### OS version

macOS 12.5

**Comment by brittandeyoung** [comment] 2022-08-16 16:33
@gberl002  I am fairly certain this is the expected behavior of this project. Since the package dependencies are not committed to source control, it is required that you install them on your machine before the Plan can run. 

I have opened a PR against the example todo app to add this step to the documentation. Does this addition resolve your open issue?

**Comment by dolanor** [comment] 2022-08-17 22:59
That's a valid quirks in our getting started.
Since we don't want (as maintainers) update the todoapp repo everytime we update the dagger engine, we will update the documentation to run this before running the CI.
The PR from @brittandeyoung updates the README of this repo, so it reflects what we have in our documentation website: https://docs.dagger.io/1200/local-dev

**Closed by dolanor** 2022-08-17 22:59 UTC
