### ISSUE TITLE
finish the services API

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#3173] opened 2022-09-28 23:45 UTC
The services API is incomplete.

Mainly:

- Convert to New Core API
- Restructure to be multi-process (just like buildkit)
- Support non-interactive mode (e.g. for launching a db etc, we don't want tty streaming etc)
- cloak attach is hardcoded to localhost
- Tests

We should either address this or remove the services API for release.

See #3123 for more details

**Comment by samalba** [comment] 2023-02-08 00:09
Duplicate of #3037

**Closed by samalba** 2023-02-08 00:09 UTC
Labels: area/engine
