### ISSUE TITLE
🖐️ Call modules in private repositories

### ISSUE THREAD

**Issue by R3DRUN3** [dagger/dagger#6781] opened 2024-02-29 17:00 UTC
### What happened? What did you expect to happen?

Hello everyone,

I'm new to Dagger and I wanted to inquire about the process of launching modules from private repositories, if possible.  
For instance, through the CLI (*dagger call*) or integration into various CI/CD engines.

Here's my scenario:
I have a private GitHub repository that contains Dagger modules, and I'd like to provide third parties with the ability to include them in their GitHub Actions pipeline.  
Is this feasible?  
I couldn't find any information regarding this in the documentation.

Thank you for your attention.

**Comment by helderco** [comment] 2024-03-02 13:25
Duplicate of https://github.com/dagger/dagger/issues/6113

**Closed by helderco** 2024-03-02 13:25 UTC
