### ISSUE TITLE
✨ Make dagger query re-use a session if present

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#5560] opened 2023-08-03 01:57 UTC
### What are you trying to do?

User request from discord:  https://discord.com/channels/707636530424053791/1136226963133055097

```
#!/usr/bin/env bash

REGISTRY_PASSWORD="monsecret"


registry_secret_id=$(dagger query <<QUERY | jq -r '.setSecret.id'
{
   setSecret(name: "registry-password", plaintext: "$REGISTRY_PASSWORD") {
     id
   }
}
QUERY
)
echo -e "$registry_secret_id"

dagger query <<QUERY
{
  secret(id: "$registry_secret_id") {
    plaintext
  }
}
QUERY
```

Trying to set a secret and using it via `dagger query`. It'd be nice if wrapping that script with a `dagger run` would be able to make it work, but seems like `dagger query` always starts a new session regardless.

### How are you currently working around this?

We've suggested the user to use `curl` instead of `dagger query`

**Comment by helderco** [comment] 2023-08-03 01:58
Duplicate of https://github.com/dagger/dagger/issues/5181

**Closed by helderco** 2023-08-03 01:58 UTC
Labels: kind/user-request
