### ISSUE TITLE
How about introducing bitbucket✨

### ISSUE THREAD

**Issue by Youngshark3** [dagger/dagger#2451] opened 2022-05-14 13:10 UTC
### What are you trying to do?

I would like to introduce bitbucket on your feature to help manage tasks. 

### Why is this important to you?

I find bitbucket so cool especially when it comes to pipelines handling. 

### How are you currently working around this?

am working with a team to improve and come up with a  good plugin to collaborate and integrate the two tools for efficient deployment.

**Comment by TomChv** [comment] 2022-07-11 17:13
@Youngshark3 Hey 👋 

Have you made some progress? Your use case looks interesting!

/cc @jpadams

**Comment by helderco** [comment] 2023-12-14 20:46
Duplicate of https://github.com/dagger/dagger/issues/5444

**Closed by helderco** 2023-12-14 20:46 UTC
Labels: kind/user-request
