### ISSUE TITLE
blog post topic - @deprecated graphql annotation, codegen and docs linting example 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3920] opened 2022-11-18 19:52 UTC
### What is the issue?

This would make a great blog post topic - https://discord.com/channels/707636530424053791/1003718839739105300/1042958220563599383

Example - 

>@deprecated is standard graphql -- codegen is transforming that in native deprecation warnings in each language
and then the go linter does the usual linting, complains about using deprecated functions
so the generated client is not doing anything special, this is regular Go tooling we integrate with by following standard deprecation warnings
In Python, @helderco formatted the comment so you even get a link to the replacement function automatically, which is pretty amazing 
https://dagger-io--3910.org.readthedocs.build/en/3910/api.html#dagger.api.gen.Host.workdir

Discord context -

**Comment by vikram-dagger** [comment] 2022-11-19 09:03
Duplicate of https://github.com/dagger/dagger/issues/3916

**Closed by vikram-dagger** 2022-11-19 09:03 UTC
Labels: area/documentation
