### ISSUE TITLE
✨ Provision to define private docker registry at global level

### ISSUE THREAD

**Issue by nipuna-perera** [dagger/dagger#2238] opened 2022-04-20 03:59 UTC
### What are you trying to do?

Use a private docker registry instead of docker hub for all images.

### Why is this important to you?

We have a corporate Artifactory implementation which proxies all docker images through a private registry. like

`myregistry.company.com/alpine:3`

which actually proxies the image via docker hub.

Currently, universe packages such as Alpine and Nginx uses hardcoded docker hub registry like 

```
docker.#Pull & {
	source: "index.docker.io/alpine:\(version)"
}
```
Dagger should standardize the way "image source" is defined for packages. I like the way it is an input in the Go package but it would be nice to be able to specify a private registry at a global level.

### How are you currently working around this?

I have to pull the image with #Docker.pull and specify the `auth` and `source` to pull images via my private registry because I can't use #Alpine out of the box.

**Comment by grouville** [comment] 2022-07-13 16:26
> client

I'm personally ok with it, as it's a simple solution to the problem and could be easily implemented. But isn't it an exception that could open a breach: we did it for this use case, why not for this new one ?

**Comment by grouville** [comment] 2022-07-13 16:28
Oh ok. I see your point of view. I can make a PR that solves this issue, with this solution. Would you be ok @helderco ?

**Comment by helderco** [comment] 2022-07-13 18:12
The way I suggested it was just to have two settings (e.g., `DOCKERHUB_AUTH_USER`, `DOCKERHUB_AUTH_PASS`) to apply in Go if they exist and the image to pull matches the `index.docker.io` registry, and has no auth. 

Since _universe_ actions pull a lot of images from the docker hub, it's very hard to override every image just to add authentication due to the rate limit.

So the scope can be very limited to just docker hub. I don't see any implications coming from this. If you're using some other registry or set of images with universe actions, you're already overriding them and you should already have your own personal/company abstraction for it. At least the most common case of hitting rate limits against the public registry gets a bit better.

If you're pulling alpine through some other means (i.e., not via the docker hub), then this wouldn't apply.

- `docker.#Pull & { source: "alpine" }` ✅ 
- `docker.#Pull & { source: "registry.gitlab.com/alpine/alpine" }` ❌ 
- `docker.#Pull & { source: "alpine", auth: _auth }` ❌ 

With `#Dockerfile` and `#Push` it's different because they're not burried in _universe_ actions. You control those so you can provide an `auth`. Still, if you have a global auth for docker hub, users may expect them there as well.

I do agree that this is a stopgap. We need a better abstraction because people need generalized auth, mirrors/proxies, etc... in their environments. This is like asking for an equivalent of `docker login` before doing `docker build`.

**Comment by shykes** [comment] 2022-07-13 19:28
Sounds good, I don't have anything better to suggest anyway, and doing nothing is not an option... 👍

**Comment by helderco** [comment] 2022-07-13 20:21
There's two issues here. 

@grouville put the other one here (https://github.com/dagger/dagger/issues/2238#issuecomment-1183360147) to fix the case of exceeded rate limiting for the docker hub, but that's different from what the OP's asking:

- Provide global setting to change the default registry globally (this issue... has more implications)
- Provide global setting with auth for the docker hub registry (should be a different issue)

As for changing the registry like OP's asking, if it's a mirror I think it's ok, but it also opens the door for potentially returning different images from what dagger's expecting (depending on the registry), leading to unexpected behavior and confusion. It has more implications and it's a use case for that better abstraction that we need, but I'm not so sure of doing the same thing as with auth for now.

**Comment by shykes** [comment] 2022-07-19 16:44
For the record, another short-term fix that might be better: move away from Docker Hub for default images in universe. Either by moving to a more generous image hosting provider that doesn't mind acting as a free CDN; or building images in such a way that a base image doesn't need to be downloaded again (build from distro packages a-la apko, or even from source). As discussed with @jpadams who will create an issue.

**Comment by TomChv** [comment] 2023-10-30 21:45
Our API has a method `WithAuthRegistry` and we answered this question in our doc (https://docs.dagger.io/faq/#how-do-i-log-in-to-a-container-registry-using-a-dagger-sdk)

**Closed by TomChv** 2023-10-30 21:45 UTC
Labels: kind/dx, kind/user-request, ecosystem, sdk/cue
