### ISSUE TITLE
SDKs fail to return leaf arrays of structs (GraphQL)

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#4398] opened 2023-01-17 23:30 UTC
### Problem
When implementing https://github.com/dagger/dagger/pull/4387 tests using the Go SDK, we realized that SDKs fail to execute some endpoints that do work as graphQL queries.

After talking with @vito, it turns out that this touches all schemas that return arrays of custom structs:
- [envVariables](https://github.com/dagger/dagger/blob/1e54736caeaf9d1f851371178d4f04a93acb545c/core/schema/container.graphqls#L83)
- [labels](https://github.com/dagger/dagger/pull/4387) (future implementation)

#### Go SDK
Given this Go SDK example:
```go
package main

import (
	"context"
	"fmt"
	"log"

	"dagger.io/dagger"
)

func main() {
	ctx := context.Background()
	c, err := dagger.Connect(ctx)
	if err != nil {
		log.Fatalf("debug: %s", err)
	}
	defer c.Close()

	labels, err := c.Container().From("nginx").EnvVariables(ctx)
	if err != nil {
		log.Fatalf("debug2: %s", err)
	}

	fmt.Println("good", labels)
}
```

We get this error: 
```shell
$ go run .  
debug2 input:1: Field "envVariables" of type "[EnvVariable!]!" must have a sub selection.

Please visit https://dagger.io/help#go for troubleshooting guidance.
```

> Error is consistent with the one encountered on current implementation of `labels`

#### GraphQL equivalent

However, the graphQL equivalent: 
```graphQL
{
  container {
    from(address: "nginx") {
      envVariables {
        name
        value
      }
    }
  }
}
```

We get: 
```json
{
  "data": {
    "container": {
      "from": {
        "envVariables": [
          {
            "name": "PATH",
            "value": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          }
        ]
      }
    }
  }
}
```

### Why didn't we see it ?

Most of container tests have been implemented as graphQL queries, thus making us unaware of this problem.

cc @vito @aluzzardi

**Comment by helderco** [comment] 2023-01-18 00:11
Duplicate of #3457

**Closed by helderco** 2023-01-18 00:11 UTC
Labels: kind/bug, area/sdk

**Comment by grouville** [comment] 2023-01-18 00:26
> Duplicate of #3457

Feeling dumb to have not checked 👼 Thanks

**Comment by helderco** [comment] 2023-01-18 00:32
Yeah, old issue... this is the second duplicate 🙂
