### ISSUE TITLE
Confusing cue error

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2146] opened 2022-04-12 02:42 UTC
Reported today on discord:

![FB04841C-9ED7-4609-84F6-BF9F3CA5A772](https://user-images.githubusercontent.com/29565/162868666-4f2ccc7f-6f92-4806-b3e3-cc27ac53171b.jpeg)

![A99E2C81-D863-49B1-A304-DC925B3FBFEE](https://user-images.githubusercontent.com/29565/162868579-59adf3d6-1516-4c50-a0e3-eaab9446b2f4.png)

**Comment by dolanor** [comment] 2022-05-02 12:53
What can we do in this case?
Add more context, like `docker.#Push.registry field does not exist`?

**Comment by shykes** [comment] 2022-05-10 17:12
> What can we do in this case?
> Add more context, like `docker.#Push.registry field does not exist`?

Good question.

* This error is definitely not the worst we've had
* Yes more context would be useful, but we already give user the most important: path where there is an error (`actions.deploy`) and the actual error (`field not allowed: registry`).
* The low-hanging fruit is to remove the useless pre-amble: `10:03AM FTL failed to load plan: ` makes sense from a logging point of view, but as a user-facing error message it is purely noise.

Instead of this:

> `10:03AM FTL failed to load plan: actions.deploy: field not allowed: registry: `

We should print this:

> `Error: actions.deploy: field not allowed: registry`

**Comment by dolanor** [comment] 2022-06-01 08:42
So we should check if this execution is run inside a terminal or not, and if yes, we remove the log prefix (with level + timestamp)?
Do we do that in all log formats (plain + tty)?

**Comment by dolanor** [comment] 2022-06-01 08:55
I'm closing this as a duplicate of #2492 ? (which has a clearer title)

If there some subitems that really require our attention, let's create new issues out of this one.

**Closed** 2022-06-01 08:58 UTC
Labels: kind/bug
