### ISSUE TITLE
Dagger fails when using podman

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3288] opened 2022-10-07 16:30 UTC
When using dagger in podman, it fails with the following error:

```
Error: short-name resolution enforced but cannot prompt without a TTY
```

This seems to be caused by the buildkit auto-install, which pulls an image from Docker Hub using its short name (eg `foo` instead of `index.docker.io/foo`). Podman has modified the behavior of short names in such a way that some podman users don't get 100% compatibility with docker.

The root cause is a defect in Podman's compatibility with Docker. However there is zero chance that Red Hat will fix this defect, which leaves us with two options:

1) Abandon support for podman
2) Work around podman's compatibility defect

**Comment by marcosnils** [comment] 2022-10-07 18:33
Not to much to discuss here. I'd say that eventually it'd be nice to have some sort of "hook" mechanism in the CLI that delegates the buildkit provisioning process to the user (if they decide to do this) so we don't have to potentially add support for any container runtime out there (not that there's plenty). 

This would be a `docker-machine` like flow but instead of Dagger being in charge of provisioning the buildkit dependency, that will be responsibility of the user. Dagger will only `exec` a script or binary the user supplies and it could use the `BUILDKIT_HOST` returned in the `stdout`.

**Comment by nemith** [comment] 2022-10-07 19:35
A workaround is to modify your podman settings for the following:

1. open /etc/containers/registries.conf
2. Change short-name-mode="enforcing" to short-name-mode="permissive"

However making the docker image Fully qualified would work for podman's default "enforcing" settings as well as be backwards compatable with docker.  

After making that change some simple testing with Go seem to work no problem.  

> The root cause is a defect in Podman. However there is zero chance that Red Hat will fix this defect, which leaves us with two options:

This is **NOT** a defect and is intentional and by design.  It should be no surprise that an open standard container runtime doesn't want to be tied to a registry from a commercial offering.  This is pretty well documented https://www.redhat.com/sysadmin/container-image-short-names

I would like to continue to run podman with "enforcing" short-name mode on my system and it would allow podman to work out out of the box and with docker desktop going to a paid model soon I think podman will see more adoption (it is supported on OS X now as well).

> Not too much to discuss here. I'd say that eventually it'd be nice to have some sort of "hook" mechanism in the CLI that delegates the buildkit provisioning process to the user (if they decide to do this) so we don't have to potentially add support for any container runtime out there (not that there's plenty).

With a few exceptions podman is very compatible with docker so I wouldn't overthink support here.   FQ image name would support both runtime for the out-of-box config and be clear on the source registry to boot.

**Comment by shykes** [comment] 2022-10-07 22:04
> However making the docker image Fully qualified would work for podman's default "enforcing" settings as well as be backwards compatable with docker.

Yes, this seems like the simplest option. Another option is simply to run buildkit yourself on podman, and set `BUILDKIT_HOST` before running dagger. Then dagger will not need to call docker nor podman at all, making the problem go away.

> > The root cause is a defect in Podman. However there is zero chance that Red Hat will fix this defect, which leaves us with two options:
> 
> This is **NOT** a defect and is intentional and by design. It should be no surprise that an open standard container runtime doesn't want to be tied to a registry from a commercial offering. This is pretty well documented https://www.redhat.com/sysadmin/container-image-short-names

You can't have your cake and it it too. Podman advertises itself as a drop-in replacement. Their website even says this:

> Simply put: alias docker=podman

Well, short image names with a universal meaning are a *fundamental* feature of the Docker experience from the very beginning. Podman, the "docker alias", breaks compatibility with Docker's short image names. Compatibility promised but not delivered: that's a defect. The fact that it's an intentional defect, by design, makes it worse.

**Comment by nemith** [comment] 2022-10-07 22:54
I don't quite understand the animosity towards podman here. If it isn't a priority right now for the dagger team I can understand but this is a pretty minor difference that was made for what the podman team (which is not synonymous with redhat) thought was better security and better clarity.  To support this minor difference it's a minor change.  I have a work around, but thought dagger would like to be more inclusive to what is a really fast and growing docker replacement. 

(Side note i run podman as my build enviroment should not require kernel level root access via a deamon to run. Esp with images downloaded from the internet.  I think this is not something to trivially overlook as being "redhat being redhat" or whatever this attitude towards podman is)

That being there are workarounds and perhaps just documenting them is fine (either via the alias or "permissive" setting to emulate docker's behavior).

However it's probably not worth going down the merits of podman vs docker for such a trivial issue.  If you don't feel like even supporting podman at all then it's probably ok just to close the issue.

**Comment by grouville** [comment] 2022-10-07 23:11
With the embedding of Buildkit, I think this problem will disappear. Adding a Podman provisioner shouldn't be that hard, I already saw the [connector](https://github.com/moby/buildkit/tree/4e69662758446c7dc0e6de2bc1f7973d03bacbed/client/connhelper/podmancontainer)
Ping to keep trace: https://github.com/dagger/dagger/issues/3058

**Comment by marcindulak** [comment] 2022-10-08 11:11
Disabling short image names may be needed for enterprise customers - there explicit, full registry names may be required to control the source of images https://www.redhat.com/en/blog/be-careful-when-pulling-images-short-name

**Comment by shykes** [comment] 2024-03-26 19:30
@grouville @levlaz  do you know if this is solved now?

**Comment by zmc** [comment] 2024-05-08 21:09
I briefly tried to get Dagger's quickstart to work on macOS, not knowing docker was a hard requirement; I use podman. I did not manage to get past:
```
WRN failed to resolve image; falling back to leftover engine error="error getting credentials - err: exec: \"docker-credential-desktop\": executable file not found in $PATH, out: ``"
Error: start engine: no fallback container found
```
Running in debug mode didn't reveal _which_ image it was looking for, so I manually pulled `ghcr.io/dagger/engine`, but that didn't change the result.

**Comment by marcosnils** [comment] 2024-05-13 15:03
@zmc  by any chance do yoi have a ~/.docker/config.json file in your machine? Can you try renaming that and trying again to see if that works?

**Comment by zmc** [comment] 2024-05-13 20:48
> @zmc by any chance do yoi have a ~/.docker/config.json file in your machine? Can you try renaming that and trying again to see if that works?

I did, and despite the fact that it only contained `{"credsStore": "desktop"}`, moving it out of the way did fix things - and this was with podman; I don't have docker installed at all. Thanks!

**Comment by jedevc** [comment] 2024-11-15 17:27
Going to close this issue out, since I think the original issue is resolved.

Any further compat issues with podman are welcome, but we should split them into separate issues :tada:

**Closed by jedevc** 2024-11-15 17:27 UTC
