### ISSUE TITLE
Lazy executions are confusing to understand and sometimes don't work as expected

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#4668] opened 2023-02-28 17:37 UTC
## Summary

Developers are often confused by a property of the Dagger engine called "laziness": pipelines are executed at the latest possible moment, to maximize performance. There are several dimensions to this problem; below is an overview of different dimensions, and status of possible solutions.

| Issues                                      | Proposals                |
| ------------------------------------------- | ------------------------ |
| [No `withExec`](#with-exec)                 | <li>#4833</li>                    |
| [`Dockerfile` build (without exec)](#build) | <li>#5065</li>                    |
| [Implicit query execution](#implicit)       | <li>#5065</li>                    | 
| [Multiple ways to execute](#multiple)       | “Pipeline builder” model | 
| [Documentation](#docs)                      | <li>#3617</li>                    |

## <a name="with-exec"></a>Issue: no `withExec`

We had some users report that part of their pipeline wasn't being executed, for which they had to add a `WithExec(nil)` statement for it to work:

```go
_, err := c.Container().Build(src).ExitCode(ctx)  // doesn't work
_, err := c.Container().From("alpine").ExitCode(ctx)  // same thing
```

### Explanation

Users may assume that since they know there’s an `Entrypoint`/`Cmd` in the docker image it should work, but it’s just updating the dagger container metadata. There’s nothing to run, it’s equivalent to the following:

```go
_, err := ctr.
    WithEntrypoint([]string{}).
    WithDefaultArgs(dagger.ContainerWithDefaultArgsOpts{
        Args: []string{"/bin/sh"},
    })
    ExitCode(ctx) // nothing to execute!
```

`ExitCode` and `Stdout` only return something for the **last executed command**. That means the equivalent of a `RUN` instruction in a `Dockerfile` or running a container with `docker run`.

### Workaround

Add a `WithExec()` to tell dagger to execute the container:

```diff
_, err := client.Container().
    Build(src).
+   WithExec(nil).
    ExitCode(ctx)
```

The empty (`nil`) argument to `WithExec` will execute the **entrypoint and default args** configured in the dagger container.

> **Note**
> If you replace the `.ExitCode()` with a `Publish()`, you see that `Build()` is called and the image is published, because `Publish` doesn’t depend on execution but `Build` is still a dependency.

The same is true for a bound service:

```diff
db := client.Container().From("postgres").
     WithExposedPort(5432).
+    WithExec(nil)
ctr := app.WithServiceBinding("db", db)
```

Here, `WithServiceBinding` clearly needs to execute/run the *postgres* container so that *app* can connect to it, so we need the `WithExec` here too (with `nil` for default entrypoint and arguments).

### Proposals

To avoid astonishment, a fix was added (#4716) to raise an error when fields like `.ExitCode` or `.WithServiceBinding` (that depend on `WithExec`) are used on a container that hasn’t been executed.

However, perhaps a better solution is to implicitly execute the entrypoint and default arguments because if you’re using a field that depends on an execution, we can assume that you mean to execute the container.

This is what #4833 proposes, meaning the following would now work as expected by users:

```go
// ExitCode → needs execution so use default exec
_, err := c.Container().From("alpine").ExitCode(ctx)

// WithServiceBinding → needs execution so use default exec
db := client.Container().From("postgres").WithExposedPort(5432)
ctr := app.WithServiceBinding("db", db)
```

```[tasklist]
### No `withExec`
- [x] #4716
- [ ] #4833
```

## <a name="build"></a>Issue: `Dockerfile` build (without exec)

Some users just want to test if a `Dockerfile` build succeeds or not, and **don’t want to execute the entrypoint** (e.g., long running executable):

```go
_, err = client.Container().Build(src).ExitCode(ctx)
```

In this case users are just using `ExitCode` as a way to trigger the build when they also don’t want to `Publish`. It’s the same problem as above, but the intent is different.

### Workarounds

With #4919, you’ll be able to skip the entrypoint:

```go
_, err = client.Container().
    Build(src).
    WithExec([]string{"/bin/true"}, dagger.ContainerWithExecOpts{
        SkipEntrypoint: true,
    }).
    ExitCode(ctx)
```

But executing the container isn’t even needed to build, so `ExitCode` isn’t a good choice here. It’s just simpler to use another field such as:

```diff
- _, err = client.Container().Build(src).ExitCode(ctx)
+ _, err = client.Container().Build(src).Rootfs().Entries(ctx)
```

However this isn’t intuitive and is clearly a workaround (not meant for this).

### Proposal

Perhaps the best solution is to use a general synchronization primitive (#5065) that simply forces resolving the laziness in the pipeline, especially since the result is discarded in the above workarounds:

```diff
- _, err = client.Container().Build(src).ExitCode(ctx)
+ _, err = client.Container().Build(src).Sync(ctx)
```

```[tasklist]
### `Dockerfile` build (without exec)
- [x] #4919
- [ ] #5065
```

## <a name="implicit"></a>Issue: Implicit query execution

Some functions are “lazy” and don’t result in a [query execution](http://spec.graphql.org/October2021/#sec-Execution) (e.g., `From`, `Build`, `WithXXX`), while others execute (e.g., `ExitCode`, `Stdout`, `Publish`).

It’s not clear to some users which is which.

### Explanation

The model is implicit, with a “rule of thumb” in each language to hint which ones execute:

- **Go:** functions taking a context and returning an error
- **Python** and **Node.js:** `async` functions that need an `await`

Essentially, each SDK’s codegen (the feature that introspects the API and builds a dagger client that is idiomatic in each language) **transforms [leaf fields](http://spec.graphql.org/October2021/#sec-Leaf-Field-Selections) into an implicit API request** when called, and return the **value from the response**.

So the “rule of thumb” is based on the need to make a request to the GraphQL server, the problem is that it may not be immediately clear and the syntax can vary depending on the language so there’s different “rules” to understand.

This was discussed in:
- #3555
- #3558

### Proposal

The same [Pipeline Synchronization](https://github.com/dagger/dagger/issues/5065) proposal from the previous issue helps make this a bit more explicit: 
```go
_, err := ctr.Sync(ctx)
```

```[tasklist]
### Implicit query execution
- [x] #3555
- [x] #3558
- [ ] #5065
```

## <a name="multiple"></a>Issue: Multiple ways to execute

“Execution” sometimes mean different things:
- **Container execution** (i.e., `Container.withExec`)
- **[Query execution](http://spec.graphql.org/October2021/#sec-Execution)** (i.e., making a request to the GraphQL API)
- **”Engine” execution** (i.e., doing actual work in BuildKit)

The *ID* fields like `Container.ID` for example, make a request to the API, but don’t do any actual work building the container. We reduced the scope of the issue in the SDKs by avoiding passing IDs around (#3558), and keeping the pipeline as lazy as possible until an output is needed (see [Implicit query execution](#implicit) above).

More importantly, users have been using `.ExitCode(ctx)` as the goto solution to “synchronize” the laziness, but as we’ve seen in the above issues, it triggers the container to execute and there’s cases where you don’t want to do that. 

However, adding the general `.Sync()` (#4205) to fix that may make people shift to using it as the goto solution to “resolve” the laziness instead (“synchronize”), which actually makes sense. The problem is that we now go back to needing `WithExec(nil)` because `.Sync()` can’t assume you want to execute the container.

That’s a catch 22 situation! **There’s no single execute function** to “rule them all”.

It requires the user to have a good enough grasp on these concepts and the Dagger model to chose the right function for each purpose:

```go
// exec the container (build since it's a dependency)
c.Container().Build(src).ExitCode(ctx)

// just build (don't exec)
c.Container().Build(src).Sync(ctx)
```

### Proposal

During the “implicit vs explicit” discussions, the proposal for the most explicit solution was for a “pipeline builder” model (https://github.com/dagger/dagger/issues/3555#issuecomment-1301327344). 

The idea was to make a clear separation between **building** the lazy pipeline and **executing** the query:

```go
// ExitCode doesn't implicitly execute query here! Still lazy.
// Just setting expected output, and adding exec as a dependency.
// Build is a dependency for exec so it also runs.
q := c.Container().Build(src).ExitCode()

// Same as above but don't care about output, just exec.
q := c.Container().Build(src).WithExec(nil)

// Same as above but don't want to exec, just build.
q := c.Container().Build(src)

// Only one way to execute query!
client.Query(q)
```

### Downsides
- It’s a big **breaking change** so it’s not seen as a viable solution now
- No great solution to grab output values
- More boilerplate for simple things

### Solution

Embrace the laziness!

## Issue: <a name="docs"></a>Documentation

We have a guide on [Lazy Evaluation](https://docs.dagger.io/api/975146/concepts#lazy-evaluation) but it’s focused on the GraphQL API and isn’t enough to explain the above issues.

We need better documentation to help users understand the “lazy DAG” model (https://github.com/dagger/dagger/issues/3617). It’s even more important if the “pipeline builder” model above isn’t viable.

```[tasklist]
### Documentation
- [x] #3622
- [ ] #3617
```

## Affected users

These are only some examples of users that were affected by this:

- from @RonanQuigley
  > DX or a Bug: In order to have a dockerfile's entrypoint executed, why did we need to use a dummy withExec? There was a unamious 😩 in our team call after we figured this out. 
- https://discord.com/channels/707636530424053791/708371226174685314/1079926439064911972
- https://discord.com/channels/707636530424053791/1080160708123185264/1080174051965812766
- https://discord.com/channels/707636530424053791/1080160708123185264/1080174051965812766
- #5010

**Comment by cpdeethree** [comment] 2023-03-01 17:19
Spark has a similar concept as Dagger when it comes to lazy evaluation. It's probably worthwhile to look at how they handle this because when using their API it is much more obvious what is lazily evaluated and what is not:

https://www.mikulskibartosz.name/difference-between-transformation-and-action-in-apache-spark/

**Comment by helderco** [comment] 2023-03-01 17:37
> When we look at the Spark API, we can easily spot the difference between transformations and actions. If a function returns a DataFrame, Dataset, or RDD, it is a transformation. If it returns anything else or does not return a value at all (or returns Unit in the case of Scala API), it is an action.

We have similar rules, that were discussed in:
- https://github.com/dagger/dagger/issues/3555
- https://github.com/dagger/dagger/issues/3558

The consensus at the time it was closed was that we wait for more feedback from users to know if we need to adjust.

Summary:
- If a method **returns a leaf value** (primitive, e.g., string, integer...), **than it executes** the query
  - Python hint: If it returns a coroutine (you need to `await` it), it's a leaf and get's executed
  - NodeJS hint: same as Python
  - Go hint: If you need to pass the context and capture an error, it's a leaf and get's executed
- Exception: if it's an `.id()` a GraphQL query gets executed, but no BuildKit build is triggered
  - We solved it by hiding id's or avoiding the need to use them directly, in the SDKs

You have hints in editors' autocomplete for all of them. Meaning that the editor (and reference docs) help you know which ones need to be `await`ed, for example, thus leading to query execution.

**Comment by samalba** [comment] 2023-03-02 23:27
> snippet to repro:
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"os"
> 
> 	"dagger.io/dagger"
> )
> 
> func main() {
> 	ctx := context.Background()
> 	c, _ := dagger.Connect(ctx, dagger.WithLogOutput(os.Stderr))
> 
> 	dir := c.Container().WithNewFile("Dockerfile", dagger.ContainerWithNewFileOpts{
> 		Contents: `FROM alpine as final
> 		RUN echo hello`,
> 	}).Directory(".")
> 	_, err := c.Container().Build(dir, dagger.ContainerBuildOpts{Target: "final"}).ExitCode(ctx)
> 	if err != nil {
> 		panic(err)
> 	}
> }
> ```
> 
> ^ when executed, the `Build` operation will never be invoked.

In this example, it's tricky because there is actually nothing to run, this is why the Build is not invoked. If you replace the `.ExitCode()` with a `Publish()`, you see that the build is called and the image is published.

```
_, err := c.Container().Build(dir, dagger.ContainerBuildOpts{Target: "final"}).WithExec([]string{"true"}).ExitCode(ctx)
```

Or if you inject a `.WithExec()` before the `.ExitCode()`, the Build is also invoked.

```
_, err := c.Container().Build(dir, dagger.ContainerBuildOpts{Target: "final"}).Publish(ctx, "ttl.sh/random12312342345435:1m")
```

In other term a single `Build()` has the same effect as a `.WithXXX()` with no leaf value, it does not execute anything. The behavior is not a bug, but it's confusing.

**Comment by shykes** [comment] 2023-03-03 00:30
> We have similar rules, that were discussed in:
> 
> * [codegen: Chaining syntax - When to execute query (i.e., implicit vs explicit)? #3555](https://github.com/dagger/dagger/issues/3555)

Oh boy. This one brings back memories...

**Comment by vito** [comment] 2023-03-03 15:50
Just noting @phroggyy ran into this in Discord:

> with the new c2c networking, do I need to call any particular function to run the dependency container? Currently running into an issue:
>
> ```
> "message":"start  (aliased as db): service exited before healthcheck"
> ```

Note the lack of a hostname in `start <hostname> (<aliases>):`. A missing hostname means `WithExec(nil)` was never called, probably something like this:

```go
client.WithServiceBinding("db", c.Container().From("postgres"))
```

The fix:

```go
client.WithServiceBinding("db", c.Container().From("postgres").WithExec(nil))
```

As others have mentioned this is technically correct, but a little less than helpful. Lots of folks are tripping on it lately. @mircubed @d3rp3tt3 I think this should be pretty high priority at this point (~3 folks tripped on it in the past few days).

No one has suggested this so I may be preaching to the choir, but I'm very hesitant to have Dagger automatically figure out what you're trying to do and do it for you. That can make the mental model even harder to grok. My preference would be for us to detect these states and provide a helpful error message so the user understands the mental model in the end.

My suggestion:

* `ExitCode`, `Stdout`, and `Stderr` currently return `null` if the container has not run yet. I think we should just make these return an error. It is far more likely at this point to be a bug rather than a useful state to program against. Making things worse, the Go SDK currently turns the `null` into a zero-value `int` or `string` which is indistinguishable from a silent successful exit. (:scream:)
* Binding a container with a blank hostname should error, as it means the container wasn't told to `Exec`.

**Comment by helderco** [comment] 2023-03-03 15:56
I agree. Erroring in those conditions would be more useful and clear.

**Comment by vito** [comment] 2023-03-03 16:06
Another thought I had is that this is a consequence of having `Container` represent both images and container execs. If we had a distinct `Image` type, `From()` and `Build()` would return an `Image` which doesn't even have `ExitCode`/`Stdout`/`Stderr` and can't be passed to `WithServiceBinding`.

A bit of a dramatic change at this point and I'm not sure if it's worth it, just another option to consider. It seems nice to make invalid states unrepresentable rather than hit them at runtime.

**Comment by helderco** [comment] 2023-03-03 18:14
> "Container is an Image (and inherits all properties), but Image is not a Container".

Yeah, that makes sense.

**Comment by samalba** [comment] 2023-03-06 20:57
@vito or @helderco Does any one of you have some bandwidth to write a proposal to address this one?

**Comment by vito** [comment] 2023-03-06 23:20
@samalba It's a small enough change so I'll just submit a PR for my proposal at the end of https://github.com/dagger/dagger/issues/4668#issuecomment-1453732766 and we can decide its fate in the PR

**Comment by shykes** [comment] 2023-03-08 00:23
#4716 is a great first step in reducing the damage, but I think closing this is premature. I think laziness is still confusing, it's worth keeping this open to discuss further improvements.

For example: when an image has an entrypoint or default args, shouldn't it use that to resolve `stdout`, `exitCode` or `serviceBinding`?

**Comment by vito** [comment] 2023-03-08 03:26
@shykes Woops, overzealous magic comment, thanks for reopening :+1: 

> For example: when an image has an entrypoint or default args, shouldn't it use that to resolve `stdout`, `exitCode` or `serviceBinding`?

I alluded to this here:

> No one has suggested this so I may be preaching to the choir, but I'm very hesitant to have Dagger automatically figure out what you're trying to do and do it for you. That can make the mental model even harder to grok. My preference would be for us to detect these states and provide a helpful error message so the user understands the mental model in the end.

But I could probably be talked into it. For example maybe I see "Image is subset of Container" because I'm too close to the problem and know the nitty-gritty details. Doing the opposite and consciously blurring that line could be beneficial, assuming there are no downsides. (Don't have time to think of examples at the moment.)

**Comment by helderco** [comment] 2023-03-10 19:08
> For example: when an image has an entrypoint or default args, shouldn't it use that to resolve `stdout`, `exitCode` or `serviceBinding`?

Yes that makes sense to me. It's a bit weird to need `.WithExec(nil)` when you have an entrypoint. For example, the common building from a `Dockerfile` example:

```go
image := c.Client.Container().Build(dir)
out, err := image.Stdout(ctx)  // expected error because you know there's an entrypoint in the Dockerfile
```

**Comment by vito** [comment] 2023-03-17 15:21
Relaying a [report](https://canary.discord.com/channels/707636530424053791/708371226174685314/1085786722505347223) from @morlay in Discord who was affected by the change to raise an error.

They were using `Build().ExitCode(ctx)` to force the `Build()` to happen. Their intent is actually to *ignore* its `ENTRYPOINT` or `CMD` and just see if the image is able to build. I suggested adding `WithExec(nil)` but they said that causes it to hang, because it runs the entrypoint.

It seems like we need an intuitive way of un-lazying `Build()`. I'm guessing this will come up for anyone that was using `Dockerfile` as their test runner before and needs to wrap it so they can gradually adopt Dagger. I suggested doing something silly like `Build().Rootfs().Entries(ctx)` for now.

**Comment by RonanQuigley** [comment] 2023-03-23 14:30
> Relaying comments from a user whose colleagues are trying Dagger:

I was speaking to Jeremy about this one.

Why not have a single command to trigger execution? You wouldn't have all this uncertainty around what calls are lazily executed vs those that are. 

Since you're using graphql, maybe `resolve()` would be a worthwhile name. Unless there's a technical reason for this?

**Comment by shykes** [comment] 2023-03-23 20:22
> > For example: when an image has an entrypoint or default args, shouldn't it use that to resolve `stdout`, `exitCode` or `serviceBinding`?
> 
> I alluded to this here:
> 
> > No one has suggested this so I may be preaching to the choir, but I'm very hesitant to have Dagger automatically figure out what you're trying to do and do it for you. That can make the mental model even harder to grok. My preference would be for us to detect these states and provide a helpful error message so the user understands the mental model in the end.
> 
> But I could probably be talked into it. For example maybe I see "Image is subset of Container" because I'm too close to the problem and know the nitty-gritty details. Doing the opposite and consciously blurring that line could be beneficial, assuming there are no downsides. (Don't have time to think of examples at the moment.)

I opened an issue to continue this particular path: https://github.com/dagger/dagger/issues/4833

I 100% think we should do this, it's just weird that we don't IMO.

**Comment by shykes** [comment] 2023-03-23 20:28
> Why not have a single command to trigger execution? You wouldn't have all this uncertainty around what calls are lazily executed vs those that aren't.
> 
> Since you're using graphql, maybe `resolve()` would be a worthwhile name. Unless there's a technical reason for this?

There's a whole separate evolutionary path which we *could* follow, that would give us that. I explored it here: https://github.com/dagger/dagger/issues/3555#issuecomment-1301327344

We decided against it in this iteration of the SDKs. Alternative SDKs or client libraries could still explore it, the GraphQL API would support it just fine. But it would be a significant break from our current DX, not to mention I failed to get consensus around it :)

Separately, there is an incremental path we can (and IMO should) follow, that doesn't break the current DX: just add an optional `lazy: bool` argument to `withExec`, `dockerBuild`, `git`, `container { from }`, and any other operation that may be useful to explicitly trigger right away. If the caller sets this flag, the engine is required to resolve it immediately.

I may be missing something, but it seems to me that 👆 would solve 90% of our "laziness is confusing" issues, in an intuitive way?

thoughts @vito @aluzzardi @sipsma ?

**Comment by shykes** [comment] 2023-03-29 15:43
> When you need to execute something you need to pass the context and get the error. In Python and JS you need to await the coroutine/promise. So these methods have a different signature, it's not enough to add that parameter.

Sorry I didn’t understand that. Passing a `lazy: bool` parameter is not possible, or not convenient, or possible but doesn’t solve the problem? I didn’t get it.

**Comment by helderco** [comment] 2023-03-29 17:17
I meant it's not possible because methods that send a request to the API have different signatures (context, return/raise error, coroutine/promise).

**Comment by helderco** [comment] 2023-04-24 14:23
I just updated the description with a **compilation of all the issues** that I see related to this, with their explanations, workarounds and proposed solutions.

### Notes
- The summary acts a a table of contents so you can click the issue name to jump to it's section.
- Let me know if anyone has anything to add or change.
- Whenever possible, use the proposals to further discussion o those solutions.

**Comment by shykes** [comment] 2023-05-01 22:46
I updated the summary to reference #5065, which has a narrower scope than ~~#4205~~. This is because the multi-part nature of the original proposal has complicated downstream design discussions a lot. As discussed with @helderco, decoupling the design discussions will make it easier to ship a solution to this problem.

**Comment by cpdeethree** [comment] 2023-07-19 04:51
As an end user I can say that I’ve switched to using sync() in my pipelines and it makes a lot more sense now than it did before. I feel pretty confident that the UX improvement has resolved the issue, at least to me, though the docs should be improved to explain what’s going on, as Helder mentioned. So I will second closing this issue

**Comment by helderco** [comment] 2023-07-21 21:14
I'm closing for now to focus on the documentation in https://github.com/dagger/dagger/issues/3617. Reopen if there's anything else.

**Closed by helderco** 2023-07-21 21:14 UTC
Labels: kind/dx, needs/discussion, PM
