### ISSUE TITLE
🐞 panic: not properly initialized state

### ISSUE THREAD

**Issue by nicolaiunrein** [dagger/dagger#2326] opened 2022-04-27 09:37 UTC
### What is the issue?

You get unhelpful error messages for uninitialized state!

### Log output

```text
panic: not properly initialized (state: unprocessed, value: <nil>)

goroutine 88 [running]:
cuelang.org/go/cue.makeValue(0xc00007fea0, 0xc00127aa20, 0x0, 0xc000000a91, 0x70d88d, 0xc0010be6a0)
        /home/runner/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/cue/types.go:668 +0x137
cuelang.org/go/cue.Value.LookupPath(0xc00007fea0, 0xc00104fcb0, 0x0, 0xc0010be6b0, 0x1, 0x1, 0xc0010be660, 0x0, 0xc000100000)
        /home/runner/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/cue/query.go:80 +0x16b
go.dagger.io/dagger/compiler.(*Value).LookupPath(0xc00137fa40, 0xc0010be6b0, 0x1, 0x1, 0x0)
        /home/runner/work/dagger/dagger/compiler/value.go:63 +0xc7
go.dagger.io/dagger/compiler.(*Value).Lookup(0xc00137fa40, 0x14aed60, 0x4, 0x0)
        /home/runner/work/dagger/dagger/compiler/value.go:68 +0x65
go.dagger.io/dagger/plan/task.(*execTask).mountAll(0x1f4afe0, 0xc00059a930, 0xc00137f9a0, 0xc00137f9a0, 0x4, 0x0, 0x0, 0x0)
        /home/runner/work/dagger/dagger/plan/task/exec.go:151 +0x113
go.dagger.io/dagger/plan/task.(*execTask).getRunOpts(0x1f4afe0, 0xc00137f320, 0xc00059a930, 0xc0013a85f0, 0x129ca20, 0xc001375d10, 0xc000114f60, 0x0)
        /home/runner/work/dagger/dagger/plan/task/exec.go:127 +0x905
go.dagger.io/dagger/plan/task.(*execTask).Run(0x1f4afe0, 0x1703e20, 0xc0013a0840, 0xc00059a930, 0xc000b4cea0, 0xc00137f320, 0x0, 0x0, 0x1703e20)
        /home/runner/work/dagger/dagger/plan/task/exec.go:35 +0x14a
go.dagger.io/dagger/plan.(*Runner).taskFunc.func1(0xc000f3aa80, 0x0, 0x0)
        /home/runner/work/dagger/dagger/plan/runner.go:174 +0x708
cuelang.org/go/tools/flow.RunnerFunc.Run(0xc00082c0e0, 0xc000f3aa80, 0x0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/tools/flow/flow.go:114 +0x30
cuelang.org/go/tools/flow.(*Controller).runLoop.func1(0xc000f3aa80)
        /home/runner/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/tools/flow/run.go:67 +0x48
created by cuelang.org/go/tools/flow.(*Controller).runLoop
        /home/runner/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/tools/flow/run.go:66 +0x1bb

```

### Steps to reproduce

```cue
package main

import (
	"dagger.io/dagger"
	"universe.dagger.io/docker"
	"universe.dagger.io/bash"
)


dagger.#Plan & {
    actions: {
        test: {
            docker.#Build & {
                steps: [
                    docker.#Pull & {
                        source: "index.docker.io/rust:1.60.0"
                    },

                    bash.#Run & {
                        mounts: {
                            "abc": dagger.#Mount & {
                                  // content: ? not specifying content here gives a runtime panic!!!
                                  source: "./_cache"
                            }
                        }
                        script: contents: "touch test"
                    },
                ]
            }
        }
    }
}


```

### Dagger version

dagger 0.2.8

### OS version

Ubuntu 20.04

**Comment by aluzzardi** [comment] 2022-04-28 01:59
Thank you for the report, @nicolaiunrein.

Turns out this is caused by using `dagger.#Mount` -- without it it doesn't panic anymore:

```cue
                        mounts: {
                            "abc": {
                                  // content: ? not specifying content here gives a runtime panic!!!
                                  source: "./_cache"
                            }
                        }
```

@helderco @jlongtine This is weird -- using `dagger.#Mount &` in a `mount` makes CUE panic

**Comment by marcosnils** [comment] 2022-04-28 03:02
> Turns out this is caused by using `dagger.#Mount` -- without it it doesn't panic anymore:

wasn't `dagger.#Mount` moved to `core.#Mount`? 

if you change this, you get a proper error about `dest` not being set

**Comment by aluzzardi** [comment] 2022-04-28 03:12
Ah! Indeed.

This is very strange, I get the same error even with #2334 

Inspecting `value.Err()`, I see a `actions.test._dag."1"._exec.mounts.abc: incomplete cause disjunction` rather than an `undefined field`. /cc @helderco @jlongtine

**Comment by helderco** [comment] 2022-05-03 11:22
This is an interesting one. If we do this in `docker.#Run`:

```diff
-mounts: [name=string]: core.#Mount
+mounts: [name=string]: _
```

Then we get:
```console
failed to load plan: actions.test._dag."1".mounts.abc: undefined field: #Mount:
    ./_tmp/cmd.cue:21:43
```

This is passing through to `core.#Exec` where `core.#Mount` is defined.

**Comment by helderco** [comment] 2022-05-03 13:15
Here's the _incomlete cause disjunction_ we're seeing here:

```
exec cue eval x.cue -c

-- cue.mod/module.cue --
module: "example.com"

-- fn/fn.cue --
package fn

#M: {
	t: "s"
	c: string
} | {
	t: "i"
	c: int
}

-- x.cue --
package x

import "example.com/fn"

#R: {
	m: fn.#M
}

a: #R & {
	m: fn.#MM & { // typo
		c: 5
	}
}
```
```console
> exec cue eval x.cue -c
[stderr]
a.m: incomplete cause disjunction
```

**Comment by morlay** [comment] 2022-06-24 08:41
@swenzel-arc 

your error just beause of type not match

```cue
// missing define stdout type
client: commands: echo: stdout: dagger.#Secret
```

**Comment by helderco** [comment] 2023-12-14 20:41
Closing since things are much different now.

**Closed by helderco** 2023-12-14 20:41 UTC
Labels: kind/bug, kind/dx, sdk/cue
