### ISSUE TITLE
Declaratively Trust CA Certificates

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#2142] opened 2022-04-12 01:49 UTC
## Declaratively Trust CA Certificates

- As a developer, I'd love it if I could _*declaratively*_ tell dagger/buildkit that I want to trust my organization's private CA cert, so that, for example, actions like `docker.#Pull` and `docker.#Push` work with our internal registry.
  - Currently, a buildkit instance must be created manually with the private CA cert(s) mounted into it.
    - E.g. `docker run --net=host -d --restart always -v $PWD/myCA-cert.pem:/etc/ssl/certs/myCA-cert.pem --name dagger-buildkitd --privileged moby/buildkit:v0.10.0`
  - It would be an awesome DX improvement if we could just provide this as a config setting, e.g. in an environment variable like `DAGGER_TRUSTED_CA_CERTS=/path/to/myCA-cert.pem`
  - See #2016

_Originally posted by @qjcg in https://github.com/dagger/dagger/discussions/2052#discussioncomment-2514744_

**Comment by 4x0v7** [comment] 2022-04-12 11:06
I think this could integrate nicely with [step-ca](https://github.com/smallstep/certificates), perhaps even build a `dagger-ca` into dagger itself. Also allow users to use their existing private CA to sign `dagger-ca`, and automate mTLS everywhere

**Comment by dubo-dubon-duponey** [comment] 2022-04-21 01:54
None of the above of course would address the need (3.) to trust additional CA inside of `#Exec`, or provide client certs for communication with other services (again, inside `#Exec`), though I would argue that the ability to mount buildkit secrets with `#Exec` should be enough, given how specialized the use-case is for these.

**Comment by dubo-dubon-duponey** [comment] 2022-04-21 01:56
Tagging @grouville (since he has been working on `BUILDKIT_CA_CERTS`)

**Comment by sigwinch28** [comment] 2022-11-19 14:47
I'm an early adopter of the Node.JS SDK (thank you, by the way) and support for additional CA certs is something I'm really looking forward to.

I use private image registries with not-widely-trusted CAs (e.g. internal organization CAs) and I need a way to get dagger's buildkit to trust these. I can't seem to find an escape hatch at the moment.

**Comment by shykes** [comment] 2022-12-21 21:48
@sipsma can we close this as duplicate of #4217 ?

**Comment by sipsma** [comment] 2022-12-21 21:58
@shykes Yes good call, #4217  is the more "modern" 0.3 incantation of the same underlying issue, makes sense to track there now. Closing this one

**Closed by sipsma** 2022-12-21 21:58 UTC
Labels: kind/user-request, area/engine, kind/ox
