### ISSUE TITLE
✨ Publish can't access Dagger services

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#8213] opened 2024-08-22 15:21 UTC
### What are you trying to do?

Coming from: https://discord.com/channels/707636530424053791/1276185558166671431

```go
func (it *PfTools) Publish(
    ctx context.Context,
    registry *dagger.Service,
) (string, error) {

    addr, err := registry.Endpoint(ctx)
    if err != nil {
        return "", err
    }

    prodImage := dag.Container().
        From("alpine").
        // WithServiceBinding("registry", registry).
        WithExec([]string{"apk", "add", "curl"})

    _ = prodImage

    // publish to ttl.sh registry
    pubaddr, err := prodImage.Publish(ctx, fmt.Sprintf("http://%s/app/tools:latest", addr))
    if err != nil {
        return "", err
    }

    return pubaddr, nil
}
```

`dagger call publish --registry=tcp://localhost:5000`

^ this will fail as `Publish` doesn't have the ability to resolve service hostnames.

### Why is this important to you?

Similarly to other engine operations like `Git` and `Http` that do support service resolution, it'd be nice to extend this to `Publish` as well

### How are you currently working around this?

N/A

**Comment by samalba** [comment] 2024-08-27 00:16
Did you try with an ExposedPort in case Publish can reach the host?

**Comment by helderco** [comment] 2024-09-23 13:50
This is actually a part of:
- https://github.com/dagger/dagger/issues/6411

**Comment by helderco** [comment] 2024-09-24 17:17
Duplicate of https://github.com/dagger/dagger/issues/6411

**Closed by helderco** 2024-09-24 17:17 UTC
Labels: kind/user-request
