### ISSUE TITLE
🖐️ Python modules: dagger behind a corporate proxy

### ISSUE THREAD

**Issue by GiugAles** [dagger/dagger#6108] opened 2023-11-14 13:05 UTC
### What happened? What did you expect to happen?

Hi everyone,

I am running dagger:
- on Ubuntu20
- with Python 3.10.12 in a pyenv environment
- using poetry for the dependencies
-  behind a corporate proxy.
 
I am observing the following behavior:
- running https://github.com/dagger/examples/blob/main/python/basic-example/test.py with `dagger run python python/basic-example/test.py`results in
  ```
  dagger.ClientConnectionError: Failed to establish client connection to the Dagger session: Could not make request: Server disconnected without sending a response. 
  ```
When simple examples of open source software do not work out of the box, I usually suspect proxies. The traceback also mentions an httpx.py file (I can include the whole traceback, if needed). So what I did is:

- I set `NO_PROXY`, `HTTP_PROXY` and `HTTPS_PROXY` like described here https://www.python-httpx.org/environment_variables/
  - No change
- I changed  this line https://github.com/dagger/dagger/blob/main/sdk/python/src/dagger/client/_transport/httpx.py#L159 to `self.client = httpx.AsyncClient(**self.kwargs, proxies={})`
  - The before mentioned call succeeds
  - First, I added something like `"all://127.0.0.1": None,`, but it turns out that an empty dict leads to the same observed behavior

I am not sure if I am on the right track here. I am missing some configuration? Is this a bug?

**Comment by helderco** [comment] 2023-11-14 16:26
Hi, it's not a bug but we still need to make this easier for users. It's not on the Python SDK's side that you need to do any configuration, you need to rather spin up a custom engine instance which includes the configuration to connect to your proxy.

See related:
- https://github.com/dagger/dagger/issues/5240
- https://github.com/dagger/dagger/issues/4217
- https://github.com/dagger/dagger/blob/main/core/docs/d7yxc-operator_manual.md#runner-details

If you're on our Discord, you can find more examples of this:
- https://discord.com/channels/707636530424053791/1125691412097290322
- https://discord.com/channels/707636530424053791/708371226174685314/1113800867271946300

And if you need to configure the proxy in a given container in a pipeline, then you need to set `ctr.with_env_variable` appropriately for setting the proxy env vars.

**Comment by GiugAles** [comment] 2023-11-15 20:59
Hi @helderco,

Thank you for the hints. We have planned a workshop regarding dagger next week. I will try your suggestion then and provide feedback here.

**Comment by helderco** [comment] 2023-12-14 19:12
@GiugAles, I'm closing in favor of continuing on https://github.com/dagger/dagger/issues/5240.

Duplicate of https://github.com/dagger/dagger/issues/5240

**Comment by helderco** [comment] 2023-12-14 19:13
@GiugAles, I'm closing in favor of continuing on https://github.com/dagger/dagger/issues/5240.

Duplicate of https://github.com/dagger/dagger/issues/5240

**Closed by helderco** 2023-12-14 19:13 UTC
