### ISSUE TITLE
Intermittent `failed to get edge: inconsistent graph state` errors

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#6234] opened 2023-12-07 15:03 UTC
We occasionally see jobs fail with this nasty internal buildkit issue: https://github.com/moby/buildkit/issues/2303 (creating this as a place to track and follow this, and also helping discoverability for users).

```
goroutine 197 [running]:
github.com/dagger/dagger/internal/mage/util.goSDKImageTarBall(0xc000b269c0, {0x8229b1, 0x5})
	/runner/_work/dagger/dagger/internal/mage/util/engine.go:365 +0x9d6
github.com/dagger/dagger/internal/mage/util.devEngineContainer(0xc00023a080?, {0x8229b1, 0x5}, {0x0, 0x0}, {0xc00047a9c0, 0x2, 0x2})
	/runner/_work/dagger/dagger/internal/mage/util/engine.go:240 +0x8d3
github.com/dagger/dagger/internal/mage/util.CIDevEngineContainer(0xc000b269c0, {0xc000235b78, 0x1, 0xc00047a900?})
	/runner/_work/dagger/dagger/internal/mage/util/engine.go:183 +0x1c8
github.com/dagger/dagger/internal/mage/util.CIDevEngineContainerAndEndpoint({0x8ca940, 0xc00045e140}, 0xa?, {0xc000235b78?, 0x0?, 0x0?})
	/runner/_work/dagger/dagger/internal/mage/util/engine.go:141 +0x38
github.com/dagger/dagger/internal/mage/sdk.Nodejs.Generate({}, {0x8ca940, 0xc00045e140})
	/runner/_work/dagger/dagger/internal/mage/sdk/nodejs.go:108 +0x1e5
github.com/dagger/dagger/internal/mage/sdk.Nodejs.Lint.func3.1()
	/runner/_work/dagger/dagger/internal/mage/sdk/nodejs.go:65 +0x1b
github.com/dagger/dagger/internal/mage/sdk.lintGeneratedCode(0xc000179f50, {0xc000c7ff40, 0x1, 0x1})
	/runner/_work/dagger/dagger/internal/mage/sdk/all.go:103 +0x245
github.com/dagger/dagger/internal/mage/sdk.Nodejs.Lint.func3()
	/runner/_work/dagger/dagger/internal/mage/sdk/nodejs.go:64 +0x70
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 6
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:72 +0x96
exit status 2
```
From https://github.com/dagger/dagger/actions/runs/7129797816/job/19414688893?pr=6221

This is similar in style to https://github.com/dagger/dagger/issues/6111, but probably got quite a different root cause.

At the time of writing, this was last observed on dagger v0.9.3 (using https://github.com/moby/buildkit/commit/86e25b3ad8c20fc420669949f24bb86c74082b2f, which does include the latest attempts to fix https://github.com/moby/buildkit/issues/2303). This was the full config:

```
5.10.199-190.747.amzn2.x86_64
containerd://1.7.2
v1.26.10-eks
engine:v0.9.3
```

cc @sipsma

**Comment by gerhard** [comment] 2024-01-25 18:13
Just hit this now: https://github.com/dagger/dagger/actions/runs/7658677025/job/20872143977?pr=6492#step:5:415

<img width="1440" alt="image" src="https://github.com/dagger/dagger/assets/3342/fdd7769c-9588-41af-be59-88af71ab1b21">

**Comment by vito** [comment] 2024-01-30 05:08
Just hit a bunch of these, and a couple of other oddities:

* https://github.com/dagger/dagger/actions/runs/7706400452/job/21001901858#step:6:157
  * This one's weird; I swear this is after a rebase. Did it get stale data? Possible red herring.
* https://github.com/dagger/dagger/actions/runs/7706400450/job/21001901613#step:6:286
* https://github.com/dagger/dagger/actions/runs/7706400452/job/21001902309#step:6:217
* https://github.com/dagger/dagger/actions/runs/7706400450/job/21001902192#step:6:238
  * this is a flake I've seen before: `failed to get state for index 0 on copy /plugins/ipam/host-local/host-local /opt/cni/bin/host-local`
  * (path affected seems to be random ish)
* https://github.com/dagger/dagger/actions/runs/7706400455/job/21001901823#step:6:587
* https://github.com/dagger/dagger/actions/runs/7706400452/job/21001902552#step:5:238
* https://github.com/dagger/dagger/actions/runs/7706400452/job/21001901531#step:6:233

These all happened within the same suite, so I wonder if there's a common element (load? race condition?).

**Comment by jedevc** [comment] 2024-01-30 10:38
> - https://github.com/dagger/dagger/actions/runs/7706400450/job/21001902192#step:6:238

This one is https://github.com/dagger/dagger/issues/6111

> These all happened within the same suite, so I wonder if there's a common element (load? race condition?).

While I'm not sure about the same suite, I know that these all tend to occur "around the same time". I think this is a result of scheduling multiple jobs to the same dagger server in our kubernetes cluster - when one of them panics and dies, this causes a bunch of jobs to fail. I don't have a good way to confirm this though - I don't think we have the visibility to see what gets scheduled where and alongside what.

Is there anyway we could grab logs for the engine that failed? cc @matipan

**Comment by gerhard** [comment] 2024-01-31 11:11
I've been seeing this error multiple times per day. It's possible that I'm paying more attention to pipelines now, but this is getting very difficult to work around:
* https://github.com/dagger/dagger/actions/runs/7696847191/job/21029271829?pr=6504#step:6:211
* https://github.com/dagger/dagger/actions/runs/7616648176/job/21029376157?pr=6471#step:5:292
* https://github.com/dagger/dagger/actions/runs/7616648169/job/21029367111?pr=6471#step:5:350

**Comment by kjuulh** [comment] 2024-02-13 13:11
I just want to pitch in and say that we're also beginning to see this issue. A restart of the shared runner solves the issue, again it seems to occur around a merge commit for some reason.

**Comment by levlaz** [comment] 2024-03-29 17:47
We are seeing this with a team that is doing a POC of dagger right now. Is there any way to at least retry steps that fail this way?

**Comment by sipsma** [comment] 2024-04-02 09:29
Spent a very long time trying to repro this bug locally and while I have a reasonable idea of what might trigger it and hit some suspicious code paths, have not managed to actually hit the error yet. So I think we just need to add more logging and wait for it to happen again; sent a PR upstream here with some more details on my progress so far in trying to repro: https://github.com/moby/buildkit/pull/4818

> We are seeing this with a team that is doing a POC of dagger right now. Is there any way to retry a steps that fail this way?
> Or, is there any chance that we could automatically retry when this happens?

I think we just need to figure it out and fix it; we haven't really looked intensively into it until now (afaik). Worst case scenario if it's somehow the world's greatest mystery and we can't figure it out, then sure we can try mitigations but I suspect with more logging we'll be able to finally figure it out.

**Comment by levlaz** [comment] 2024-04-02 20:30
Thanks Erik, that is great to hear, I appreciate the update! Looking forward to seeing how things go.

Lev Lazinskiy
Head of Solutions @ dagger.io ( http://dagger.io )
e: ***@***.***
p: 415.470.2142

**Comment by kjuulh** [comment] 2024-04-05 18:47
Let us know how we can help debug this. We run quite a few builds and see this intermittently (I'd guess around 300+ a day or so). At least once a day or so (we're not yet on dagger cloud org wise).

**Comment by sipsma** [comment] 2024-04-26 20:59
More details in https://github.com/dagger/dagger/pull/7128, but ended up being able to very consistently repro the https://github.com/dagger/dagger/issues/6111 error locally and figured out the bug upstream, fix there https://github.com/moby/buildkit/pull/4887

I never was able to repro the `inconsistent graph state` error specifically, but based on reading the buildkit scheduler code I suspect it has the same root cause, so *hopefully* this will be fixed once upstream gets picked up and do a release. Will leave this open for now.

**Comment by sipsma** [comment] 2024-06-05 03:21
There was hope that we'd fixed this alongside the fix for https://github.com/dagger/dagger/issues/6111 but, while the other one has disappeared, this error message did pop up again unfortunately: https://github.com/dagger/dagger/pull/7517#issuecomment-2147218051

So seems to have a different root cause after all.

**Comment by jedevc** [comment] 2024-10-10 18:19
We haven't seen this one in a while - I wonder if we should close it?

**Comment by sipsma** [comment] 2024-10-10 19:28
> We haven't seen this one in a while - I wonder if we should close it?

Yeah it's been a very long time, will close until proven wrong 🙂

**Closed by sipsma** 2024-10-10 19:28 UTC
Labels: kind/flake
