### ISSUE TITLE
🐞 There is no file exported to the host machine when the execution command fails

### ISSUE THREAD

**Issue by GeitRavi** [dagger/dagger#8307] opened 2024-09-03 02:30 UTC
### What is the issue?

We are trying to run the UI Playwright tests and export the test results to the host machine. This works fine when all tests pass. However, when there is a test failure, the container exits with error code 2 and does not export the test report.

func (m *Demo1) RunTest(ctx context.Context, source *dagger.Directory) *dagger.File {

        // Connect to the Dagger eng
        container := dag.Container().
                From("mcr.microsoft.com/playwright:v1.46.1-focal").
                WithDirectory("/app", source).
                WithWorkdir("/app").
                WithEnvVariable("npm_config_yes", "true").
                WithExec([]string{"npm", "install", "-g", "npm@10.8.3"}).
                WithExec([]string{"npm", "install", "@playwright/test"}).
                WithExec([]string{"npx", "playwright", "test"})

        _,err := container.Stdout(ctx)
        if err != nil {
        return container.Directory("/app").File("results.xml")
        }
		return container.Directory("/app").File("results.xml")
		
}
Is there a way to export the report in case of failure as well.Thanks

### Dagger version

dagger v0.12.5

### Steps to reproduce

We are trying to run the UI Playwright tests and export the test results to the host machine. This works fine when all tests pass. However, when there is a test failure, the container exits with error code 2 and does not export the test report.

func (m *Demo1) RunTest(ctx context.Context, source *dagger.Directory) *dagger.File {

        // Connect to the Dagger eng
        container := dag.Container().
                From("mcr.microsoft.com/playwright:v1.46.1-focal").
                WithDirectory("/app", source).
                WithWorkdir("/app").
                WithEnvVariable("npm_config_yes", "true").
                WithExec([]string{"npm", "install", "-g", "npm@10.8.3"}).
                WithExec([]string{"npm", "install", "@playwright/test"}).
                WithExec([]string{"npx", "playwright", "test"})

        _,err := container.Stdout(ctx)
        if err != nil {
        return container.Directory("/app").File("results.xml")
        }
		return container.Directory("/app").File("results.xml")
		
}
Is there a way to export the report in case of failure as well.Thanks

**Comment by jedevc** [comment] 2024-09-03 09:56
Heya, this looks like a duplicate of https://github.com/dagger/dagger/issues/8275.

Going to close this one, and answer there.

**Closed by jedevc** 2024-09-03 09:56 UTC
