### ISSUE TITLE
Document `core.#Start`

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#2397] opened 2022-05-04 19:25 UTC
### What is the issue?

@sipsma recently merged (https://github.com/dagger/dagger/pull/2214) an initial implementation to allow Dagger to run async tasks which opens the door to do some very neat things like running DB's or any other type of dependency to fulfill e2e pipelines in Dagger. This feature has some caveats mentioned in #1258 and #2389 that we should provide initial basic documentation for to avoid unnecessary reports about things that we know we're working on or are missing now. I guess the important thing to capture now is communicating that this exists, understand how users feel interacting with the API and figure out if the long-term solution is what users expect to ultimately use. 

cc @shykes @samalba @aluzzardi @jpadams

**Comment by sipsma** [comment] 2022-05-04 21:42
I guess the choice here is between addressing some of the known issues and ***then*** creating user docs or just creating user docs right away.

Overall, I am okay with any approach but like the following the most:
1. Track known limitations/workarounds in Github issues
2. Use `core.#Start` with pilots (where a Dagger engineer is working directly with a user) and "dog-food" use cases, addressing issues as needed
3. Once we're comfortable with the feature-set and ux, add more thorough documentation and user guides to the official docs.

I think that strikes the right balance between getting useful feedback and not writing overly complicated docs about all the workarounds needed for certain use cases right now. Let me know if there's any disagreement though.

I am going to go create an issue for tracking all the follow ups, including this documentation task which I'll link back to. If we go the route I suggested above, this will help us decide what feature-set we will be comfortable with before creating user guides.

**Comment by marcosnils** [comment] 2022-05-05 00:24
> * Track known limitations/workarounds in Github issues
> * Use `core.#Start` with pilots (where a Dagger engineer is working directly with a user) and "dog-food" use cases, addressing issues as needed
> * Once we're comfortable with the feature-set and ux, add more thorough documentation and user guides to the official docs.

> I think that strikes the right balance between getting useful feedback and not writing overly complicated docs about all the workarounds needed for certain use cases right now. Let me know if there's any disagreement though.


SGTM! @jpadams @mircubed we need your help to follow this flow as much as possible :pray: cc @shykes WDYT?

**Comment by shykes** [comment] 2022-05-17 20:13
This sounds good to me. My main concern is accidentally crossing a "one way door" with our networking model. Specifically, I worry about making promises to our users (intentionally or not) about a container being reachable over the network, when in fact it is only reachable in a very specific infrastructure setup (where is buildkit running; what network setting is it running with; how is the underlying networking infrastructure setup; etc).

If too many users start relying on such an infrastructure-specific feature, then we effectively will have fragmented the platform: instead of "this works on all Dagger engines", we will start seeing "this requires a Dagger engine with the following buildkit / containerd / OS / network configuration". We must avoid this at all cost.

**Comment by marcosnils** [comment] 2022-05-17 21:40
> instead of "this works on all Dagger engines"

the way the feature works "today" it's the same on all engines. I don't see any possible fragmentation here "except" for users that want to go beyond the "limitations" that the current implementation has (i.e: accessing a task port from the Dagger host). IMO the main *issue* that we have today from our side is that those limitations are not explicitly documented (hence this issue), so users could potentially start this fragmentation "accidentally" because they don't have a clear idea what's the current "use-case" and how we're suggesting to use it so it works everywhere the same way.

**Comment by jpadams** [comment] 2022-05-18 05:45
I haven't had need for this with a Pilot yet, but I'm sure it will come up. I'll read the related issues to get educated.

**Comment by shykes** [comment] 2022-05-18 05:55
@marcosnils that makes sense to me. I don’t have a well-informed opinion on what we should document or not, ship or not, at the moment. So I just wanted to state what I personally care about. As long as my concern is understood and shared, I’m happy with any plan the team chooses 👍

**Comment by sipsma** [comment] 2022-05-18 17:10
@shykes I completely agree that ensuring Buildkit containers have a consistent networking environment (i.e. not host-dependent) is table stakes for considering this featureset completed and ready for wide use. I have related tasks and some discussion in the epic tracking issue for all this: https://github.com/dagger/dagger/issues/2398

**Comment by sipsma** [comment] 2022-05-18 20:57
@marcosnils I thought we had agreed to option 1 here: https://github.com/dagger/dagger/issues/2397#issuecomment-1118055063

The use cases, current limitations and steps needed to get to the point where we create official user docs for it are all documented in this issue: https://github.com/dagger/dagger/issues/2398

**Comment by sipsma** [comment] 2022-05-19 01:53
Just a note, I checked with Sam and confirmed that he didn't mean to change the decision on how to approach the documentation here, he just added the `priority/high` label as part of triaging, so I removed it for now given our previous decision on how to approach this. If there's still disagreement and we decide to do documentation right away then I'll re-add it as part of our upcoming documentation effort and work on it.

**Comment by mircubed** [comment] 2022-11-03 23:31
closing since we have it in #2398

**Closed by mircubed** 2022-11-03 23:31 UTC
Labels: area/documentation
