### ISSUE TITLE
🐞 Incompatible fsutil version in go sdk

### ISSUE THREAD

**Issue by kpenfound** [dagger/dagger#3367] opened 2022-10-13 21:43 UTC
### What is the issue?

Using the Go sdk on:

```
go version
go version go1.19.1 darwin/arm64
```

When I upgrade to the latest version of the go sdk:

```
go get -u go.dagger.io/dagger@d988bac
go: downloading go.dagger.io/dagger v0.2.35-0.20221013212912-d988bac25577
go: downloading golang.org/x/sys v0.0.0-20221013171732-95e765b1cc43
go: downloading google.golang.org/genproto v0.0.0-20221013201013-33fc6f83cba4
go: added github.com/moby/patternmatcher v0.5.0
go: upgraded github.com/tonistiigi/fsutil v0.0.0-20220115021204-b19f7f9cb274 => v0.0.0-20220930225714-4638ad635be5
go: upgraded go.dagger.io/dagger v0.2.35-0.20221012231743-405b55e9157c => v0.2.35-0.20221013212912-d988bac25577
go: upgraded golang.org/x/sys v0.0.0-20221010170243-090e33056c14 => v0.0.0-20221013171732-95e765b1cc43
go: upgraded google.golang.org/genproto v0.0.0-20221010155953-15ba04fc1c0e => v0.0.0-20221013201013-33fc6f83cba4
```

Go upgrades me to `fsutil v0.0.0-20220115021204-b19f7f9cb274`. When I run engine.Start while on this version of fsutil, dagger says:

```
go run ci/main.go test
# github.com/moby/buildkit/session/filesync
../../../../go/1.19.1/pkg/mod/github.com/moby/buildkit@v0.10.4/session/filesync/filesync.go:112:20: cannot use dir.Map (variable of type func(string, *types.Stat) bool) as type fsutil.MapFunc in struct literal
```

When I rollback fsutil:
```
go get github.com/tonistiigi/fsutil@b19f7f9cb274
go: downgraded github.com/tonistiigi/fsutil v0.0.0-20220930225714-4638ad635be5 => v0.0.0-20220115021204-b19f7f9cb274
```

I'm able to successfully start the engine

### Dagger version

d988bac

### OS version

macOS arm64

**Comment by sipsma** [comment] 2022-10-13 22:32
Can reproduce this and the error makes sense in that there was indeed an incompatible change here: https://github.com/tonistiigi/fsutil/blame/4638ad635be52e38af6b57952a7a5d3f938704a7/walker.go#L25

What makes less sense to me is that the change in question happened 5 months ago, so I don't really get why this would not have appeared earlier.

dagger's dep on fsutil got moved from //indirect to direct by my recent change (though I did not do that by hand, it must have happened automatically): https://github.com/dagger/dagger/blame/cloak/go.mod#L25
* I have no idea if that's related, it didn't change the version, will poke a bit more though

If that leads nowhere I'll think about what options we can give users in the mean time while this issue is sorted out. We can ask them to downgrade `fsutil` of course, but that's far from ideal, so I'll see if there's anything else

**Comment by jpadams** [comment] 2022-10-13 22:41
Confirmed almost identical error message on 
`go version go1.19 darwin/arm64`
```
# github.com/moby/buildkit/session/filesync
../../../../../go/pkg/mod/github.com/moby/buildkit@v0.10.4/session/filesync/filesync.go:112:20: cannot use dir.Map (variable of type func(string, *types.Stat) bool) as type fsutil.MapFunc in struct literal
```

**Comment by sipsma** [comment] 2022-10-13 22:47
@kpenfound I think the solution to this will be to just not include `-u` when running go get. After poking around more I think that's more meant for when you as a maintainer are trying to actually update everything (including transitive) deps to the latest version (and accepting any problems that may cause). Normal use of just adding a dependency should not include it.

If I start from an empty go mod and run these commands (with code that imports the api in my dir):
```console
go get go.dagger.io/dagger@d988bac // no -u
go mod edit -replace=github.com/docker/docker=github.com/docker/docker@v20.10.3-0.20220414164044-61404de7df1a+incompatible
go mod tidy
```

Then it all works for me.

The problem in general will be fixed when we upgrade to a new buildkit release (their master branch already has been updated for the incompatible change in fsutil).

Let me know if that works for you too.

**Comment by jpadams** [comment] 2022-10-13 23:25
Above fix works for me. Sounds like once we have the new buildkit release (wonder when they'll cut a release?) and we release our go SDK, will be just:

```
go mod init <your module>
go get go.dagger.io/dagger
go mod tidy
```

right?

**Comment by sipsma** [comment] 2022-10-14 00:13
> Above fix works for me. Sounds like once we have the new buildkit release (wonder when they'll cut a release?) and we release our go SDK, will be just:

Well we'll still need the `go mod edit` command unless something changes. That's a different problem from the one in this issue (has existed for a long time).
* As of right now, `buildkit` [master branch still has the replace](https://github.com/moby/buildkit/blob/master/go.mod#L155), so that means we'll still need it too whenever there's a next release.

But yeah once we merge into main I don't think we'll need the `@<commit>` anymore at least.

**Comment by thaJeztah** [comment] 2022-10-14 00:24
Relates to https://github.com/moby/buildkit/pull/3144

https://github.com/tonistiigi/fsutil/pull/130#issuecomment-1119794798

**Comment by sipsma** [comment] 2022-10-14 00:30
Thanks @thaJeztah ! Actually, while you're here, do you know if there's any hope for the replace of `github.com/docker/docker` to be removed from buildkit's go.mod in the future? 

Either way @jpadams @kpenfound looks like the fsutil incompatibility will be backported to a v0.10 release. However, I would still in general recommend we don't tell users to use `-u` just because other similar problems could crop up in the future.

**Comment by thaJeztah** [comment] 2022-10-14 00:35
I think for the replace to be gone, we'd need https://github.com/moby/buildkit/pull/3173 as well (but go modules may still reject the version)

Currently it looks like neither of those patches will be accepted by the BuildKit maintainers, so if you depend on both BuildKit and Docker, then it's quite possibly things won't work out 😔

**Comment by sipsma** [comment] 2022-10-14 00:43
@thaJeztah I see, thanks for the info! It's sad but also just one of those things where the go tooling should really have a better solution (but I'm sure it's complicated and all that).

**Comment by jpadams** [comment] 2022-10-14 03:46
@shykes feels like this would be a good place for a sugary cli command like:

```
dagger project init --sdk go --module foo
```
that would perform
```
go mod init foo
go get go.dagger.io/dagger@<version if needed>
go mod edit -replace=github.com/docker/docker=github.com/docker/docker@v20.10.3-0.20220414164044-61404de7df1a+incompatible
go mod tidy
```

**Comment by sipsma** [comment] 2022-10-14 04:12
@jpadams `project init` is only needed when writing extensions, but agree that as long as we are careful with user's config files (go.mod, package.json, etc.) that would be great to have. Can have a `--sugar-free` flag for when they don't want it too maybe.

I could have sworn we had an issue about project init templates (which is kind of similar-ish) but can't find it, so I made a new one here: https://github.com/dagger/dagger/issues/3368

**Comment by kpenfound** [comment] 2022-10-14 15:38
Confirmed that ditching the `-u` is what I needed, thanks @sipsma 

```
go get go.dagger.io/dagger@cf8c214
go: downloading go.dagger.io/dagger v0.2.35-0.20221014150559-cf8c214ae5ae
go: upgraded go.dagger.io/dagger v0.2.35-0.20221013212912-d988bac25577 => v0.2.35-0.20221014150559-cf8c214ae5ae
```

**Closed** 2022-10-14 15:47 UTC
Labels: kind/bug
