### ISSUE TITLE
Docker.#Build fails when chaining actions in a plan

### ISSUE THREAD

**Issue by sebasjm** [dagger/dagger#2020] opened 2022-04-04 12:15 UTC
### What is the issue?

I'm trying to build a plan like this

```
dagger.#Plan & {
  actions: {
    linux: {
      build: docker.#Build & {
     ....
   },
       updated: {
      build: docker.#Build & {
        steps: [
          linux.build,
     ...
   },
    box: {
      build: docker.#Build & {
        steps: [
          updated.build,
     ....
   }
}
```

and fails with this error

```
$ dagger do box build -p image_output.issue.cue 
9:00AM FTL failed to load plan: actions.box.build._dag."0"._dag."0": structural cycle
```

It's look like related to the private field _dag, because I can work it around using the first step as follows:

```
....
    box: {
      build: docker.#Build & {
        steps: [
          {
            output: updated.build.output
          },
      ...
    }
```

### Log output

9:00AM FTL failed to load plan: actions.box.build._dag."0"._dag."0": structural cycle

### Steps to reproduce

1. git clone https://github.com/sebasjm/dagger-testing
2. cd dagger-testing
3. dagger project init
4. dagger do box build -p image_output.issue.cue

### Dagger version

dagger devel (64cdadb8) linux/amd64

### OS version

Ubuntu 18.04.5 LTS

**Comment by helderco** [comment] 2022-04-04 12:39
Duplicate of #1466, which is about nesting instead of chaining but the underlying issue is the same (I think).

Please reopen if not the case.

**Closed by helderco** 2022-04-04 12:39 UTC
