### ISSUE TITLE
Python: increase execution timeout

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#4111] opened 2022-12-06 14:21 UTC
The default timeout for executing a query in the Python SDK is 5 min. This may be too short a default for dagger.

What are the timeouts in other SDKs?
- Go?
- Nodejs?

Is 30 mins good, or too much? What should we converge on @sipsma?

This was hit by a user doing a build.

**Comment by helderco** [comment] 2022-12-07 18:35
You can already configure the timeout, I'm just wondering about the default. `httpx`'s default is 10 sec and I pushed it to 5 min but that's too short for dagger. I can default to `None` so there's no timeout.

**Comment by helderco** [comment] 2022-12-07 19:24
To be clear this timeout is for each query, not the whole build or connection.

**Comment by cpdeethree** [comment] 2022-12-12 01:31
I ran into this when trying to create a GKE cluster with Dagger today. I agree that it should be either forever or a lot longer than 5 minutes. It also wasn't super clear what had happened because in my case it just said CANCELED in the container with no other indication that we had actually hit Dagger's timeout. It should be somehow communicated better that Dagger is the one doing this cancellation

**Comment by helderco** [comment] 2022-12-12 13:27
In _async_, the same `execution_timeout` is being used both for the event loop waiting on the async task and for the http connection.

You make a good point, I'll improve the error message to make it clear how you can change it, but I'm also thinking on defaulting to not timeout by default, which means you'd need to explicitly set one so the error message will be just a reminder.

**Comment by cpdeethree** [comment] 2022-12-12 14:14
defaulting to not timeout sounds great!

**Comment by zephyros-dev** [comment] 2022-12-19 14:50
I run a long ansible playbook in a single exec, and seems like this is the cause for the `Canceled` that happened during the run. Would love to see the PR get merged soon so I can start using dagger.

**Comment by cpdeethree** [comment] 2022-12-19 19:37
> I run a long ansible playbook in a single exec, and seems like this is the cause for the `Canceled` that happened during the run. Would love to see the PR get merged soon so I can start using dagger.

FYI, this just changes the default behavior. You can update it yourself already, a variable already exists in dagger python SDK. You don't need that PR to do it.

When you create your dagger config, specify execute_timeout value

```python
config = dagger.Config(log_output=sys.stderr, execute_timeout=300) # 300 is the default currently
```

Either specify None to make it run forever
```python
config = dagger.Config(log_output=sys.stderr, execute_timeout=None)
```
or some arbitrarily long timeout that you like:

```python
config = dagger.Config(log_output=sys.stderr, execute_timeout=9999)
```

The only thing that PR would do is make 
```python
config = dagger.Config(log_output=sys.stderr # nothing specified here for execute_timeout)
```
have Forever instead of 300 as the default behavior. Nothing's stopping you from explicitly specifying that now.

**Comment by helderco** [comment] 2022-12-19 19:49
That's already been done but you have to see the latest version: https://dagger-io.readthedocs.io/en/latest/connection.html

**Comment by zephyros-dev** [comment] 2022-12-20 03:04
Not sure how I missed the options when I tried looking through the suggestions functions from the IDE, but having proper documentation is even better. Thanks for the helps.

**Closed** 2022-12-24 00:42 UTC
Labels: size/small, sdk/python
