### ISSUE TITLE
🐞 Bash completion failing in v0.11.0

### ISSUE THREAD

**Issue by Dudesons** [dagger/dagger#7076] opened 2024-04-10 13:29 UTC
### What is the issue?

Bash completion is failing since version v0.11.0 with the following error: `Completion ended with directive ShellCompDirectiveNofileComp`
More details in this discord thread https://discordapp.com/channels/707636530424053791/1227602359547592745

### Dagger version

dagger v0.11.0 (registry.dagger.io/engine) linux/amd64

### Steps to reproduce

Install version v0.11.0
try to complete in a bash shell a dagger command.

**Comment by marcosnils** [comment] 2024-04-10 13:34
cc @helderco

**Comment by marcosnils** [comment] 2024-04-12 13:38
looks like zsh doesn't seem seem to be working also: https://discord.com/channels/707636530424053791/1228287061061271614

**Comment by samalba** [comment] 2024-08-16 19:30
Going through some issues cleaning, I tried to repro this one on a vanilla bash 5.2 with bash-completion and dagger v0.12.4 freshly installed.

```sh
$ bash
bash-5.2$ . /opt/homebrew/etc/bash_completion
bash-5.2$ . /opt/homebrew/etc/bash_completion.d/dagger
bash-5.2$ dagger
call        (Call one or more functions, interconnected into a pipeline)  install     (Install a dependency)
completion  (Generate the autocompletion script for the specified shell)  login       (Log in to Dagger Cloud)
config      (Get or set module configuration)                             logout      (Log out from Dagger Cloud)
develop     (Prepare a local module for development)                      query       (Send API queries to a dagger engine)
functions   (List available functions)                                    run         (Run a command in a Dagger session)
help        (Help about any command)                                      version     (Print dagger version)
init        (Initialize a new module)
bash-5.2$
```

It works.

I can confirm it's also fine on zsh. I'll close this one. Please re-open if you think it still happens.

**Closed by samalba** 2024-08-16 19:30 UTC
Labels: kind/bug, area/cli
