### ISSUE TITLE
🐞 Environment variables inaccessible after docker.#Set

### ISSUE THREAD

**Issue by NarendraPatwardhan** [dagger/dagger#2576] opened 2022-06-03 21:29 UTC
### What is the issue?

After using docker.#Set & { config: env: <Key>: <Value> } once inside a docker.#Build, all default environment variables such as PATH, and HOME become inaccessible for interpolation. They exist inside the resultant image when a container is spun up to check.

### Log output

9:22PM ERR system | failed to load plan: actions.test._build._dag."2"._set.config.env.PATH: invalid interpolation: undefined field: PATH:
    ./main.cue:19:24
    ./main.cue:19:52
actions.test._build._dag."2"._set.output.env.PATH: invalid interpolation: undefined field: PATH:
    ./main.cue:19:24
    ./main.cue:19:52
actions.test._build._dag."2".config.env.PATH: invalid interpolation: undefined field: PATH:
    ./main.cue:19:24
    ./main.cue:19:52
actions.test._build._dag."3"._config.input.env.PATH: invalid interpolation: undefined field: PATH:
    ./main.cue:19:24
    ./main.cue:19:52
actions.test._build._dag."3"._config.output.env.PATH: invalid interpolation: undefined field: PATH:
    ./main.cue:19:24
    ./main.cue:19:52
actions.test._build._dag."3"._defaults.config.env.PATH: invalid interpolation: undefined field: PATH:
    ./main.cue:19:24
    ./main.cue:19:52
actions.test._build._dag."3"._defaults.output.env.PATH: invalid interpolation: undefined field: PATH:
    ./main.cue:19:24
    ./main.cue:19:52
actions.test.result: invalid interpolation: undefined field: PATH:
    ./main.cue:19:24
    ./main.cue:19:52

### Steps to reproduce

```
package main

import (
	"dagger.io/dagger"
	"universe.dagger.io/docker"
)

#TestSet: {
	_build: docker.#Build & {
		steps: [
			docker.#Pull & {
				source: "ubuntu:20.04"
			},
                        docker.#Set & {
                                config: env: DEBIAN_FRONTEND: "noninteractive"
                        },
			docker.#Set & {
				input: _ // with docker.#Build you don't need to set input, but we need a reference to use below
				config: env: PATH: "/foobar:\(input.config.env.PATH)"
			},
			docker.#Run & {
				always: true
				command: {
					name: "sh"
					flags: "-c": "echo $PATH"
				}
			},
		]
	}
	result: _build.output.config.env.PATH
}

dagger.#Plan & {
	actions: test: #TestSet
}
```

Reproducible using `dagger do test`

### Dagger version

dagger 0.2.15 (d3dedae4) linux/amd64

### OS version

Ubuntu 20.04

**Comment by TomChv** [comment] 2022-06-08 08:35
The error is normal, the interpolation will be evaluated before `docker.#Set` run so `config.env` is empty at this state.

For now I do not see a solution, maybe @jlongtine has an idea?

**Comment by helderco** [comment] 2022-06-20 00:15
No, since it's `input`, it doesn't need `docker.#Set` to run. Besides, `docker.#Set` doesn't run any core actions, it's pure CUE.

I think there's a bug where the first `#Set` is clearing `env` so `env.PAHT` is not available in the next one. Need to investigate.

**Comment by d3rp3tt3** [comment] 2023-03-09 19:27
@NarendraPatwardhan , has the issue been reproduced in later versions?

**Comment by TomChv** [comment] 2023-09-01 22:18
Should we close this issue since we are focus on SDK since Cloak?

**Comment by TomChv** [comment] 2023-10-31 11:22
Outdated issue, I'm closing it since we're no longer working on CUE SDK.

**Closed by TomChv** 2023-10-31 11:22 UTC
Labels: kind/bug
