### ISSUE TITLE
Language Server for Dagger

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#825] opened 2021-07-14 17:02 UTC
It's pretty hard to write a dagger config from scratch and remember the APIs (e.g. inputs/outputs).

I typically start somewhere (e.g. copy some existing files), then look at the source code of the packages I want to use to figure out what the inputs and outputs are. I never manage to write a config without looking somewhere else (e.g. open source package or use `dagger doc`).

Having a Language Server would provide:
- Syntax Highlighting, syntax checking, on the fly errors, ...
- Auto Completion
- Inlined Docs

Something like this would be life changing:

<img width="487" alt="Screen Shot 2021-07-14 at 6 59 09 PM" src="https://user-images.githubusercontent.com/179503/125662545-3028851d-9900-46ce-b991-9051567e233e.png">

I'm not sure if a CUE Language Server would be enough or if we'd need a Dagger-specific one on top to understand domain specific concepts (e.g. inputs/outputs)

**Comment by jpadams** [comment] 2022-04-09 22:01
related: https://github.com/cue-lang/cue/issues/142

**Comment by mircubed** [comment] 2022-06-01 21:08
@aluzzardi can I close this task since it is currently being worked on in #2132?

**Comment by samalba** [comment] 2022-06-10 18:08
Closing, duplicate of #2132.

**Closed by samalba** 2022-06-10 18:08 UTC
Labels: kind/enhancement, kind/dx, initiative/onboarding
