### ISSUE TITLE
✨ improve with_exec-container observability

### ISSUE THREAD

**Issue by postamar** [dagger/dagger#5792] opened 2023-09-18 13:56 UTC
### What are you trying to do?

This is a companion issue to https://github.com/dagger/dagger/issues/5791 . While debugging that particular issue, I wanted to `tee` the stdout and stderr of a long-running `with_exec`ed process into a file, and then tail that file.

I found it painful, as a non-container-expert, while developing my application locally, to figure out how to access those files. Eventually, and thanks to your help, I was able to do so by doing `docker exec -it <the dagger engine> sh` and in there, `ps` to get the pid of the `tee` and then `nsenter -t <pid> -m -u -i -n -p` and _then_ poke around the actual container. 

I'm aware that I could have had those files in a volume. My point is, it shouldn't be that hard to access the "insides" of such a container, to exec a shell in it to do any number of routine observability/debugging/profiling tasks like attaching gdb or running a perf report. Not just shell stuff: if I could open a JMX port with a simple one-liner without having to change the pipeline definition, I'd be happy.

Sorry if this is badly worded I'm hardly a systems programmer but I guess that's kind of the point: as a dagger user, I feel that at one point I eventually _will_ want to poke around the insides of one of your containers, without needing to become an expert in cgroups and whatnot.

**Comment by TomChv** [comment] 2023-10-16 19:09
@postamar Is it somehow related to #5820? If you could simply open a shell on a container, would that fix your issue?

**Comment by TomChv** [comment] 2023-10-23 14:52
I made a demo and repro explanation on https://github.com/dagger/dagger/issues/5820#issuecomment-1775382506, let me know if this fix your problem :D

**Comment by TomChv** [comment] 2023-10-30 13:04
@postamar I'm closing this issue since it looks like a duplicate of #5820, if explanation on https://github.com/dagger/dagger/issues/5820#issuecomment-1775382506 does not fix your issue, feel free to reopen this issue with some information about what is missing 🚀

**Closed by TomChv** 2023-10-30 13:04 UTC
Labels: kind/user-request, area/engine

**Comment by postamar** [comment] 2023-10-30 17:10
Thanks @TomChv this seems great!
