### ISSUE TITLE
codegen: field ordering

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#3589] opened 2022-10-28 20:42 UTC
Field ordering in codegen is alphabetical.

This causes inconsistencies, e.g.:

https://discord.com/channels/707636530424053791/1034775679897718834

```go
maven = maven.WithMountedCache(cacheID, "/root/.m2/repository")
maven = maven.WithMountedFile("/root/.m2/settings.xml", mavenSettingsId)
```

**Proposal: Keep same field ordering as defined in the schema**

This is actually tricky to do because the introspection query returns a random order.

Solutions:

1) Patch `graphql-go` so schema field ordering is preserved in the introspection API (**preferred solution**)
2) Change codegen to no longer use introspection query. Instead, parse the schema directly, hopefully keeping the same order. Requires adding an API endpoint to retrieve the raw schema (e.g. `query { _sdl }`)

/cc @vito @sipsma @helderco

**Comment by helderco** [comment] 2022-10-28 21:38
Duplicate of https://github.com/dagger/dagger/issues/3554

**Closed** 2022-10-28 21:40 UTC
