### ISSUE TITLE
🐞 running python sdk on windows is not working

### ISSUE THREAD

**Issue by noamisraeli** [dagger/dagger#3934] opened 2022-11-20 09:39 UTC
### What is the issue?

The first snippet crashes for incompatibility with the UNIX-specific method calls when following the documentation of the python-SDK guide on a Windows machine.

### Log output

$ C:/Users/97254/AppData/Local/Programs/Python/Python311/python.exe c:/Users/97254/Documents/Programing/dagger/test.py
Traceback (most recent call last):
  File "c:\Users\97254\Documents\Programing\dagger\test.py", line 30, in <module>
    anyio.run(test)
  File "C:\Users\97254\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_core\_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\97254\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\97254\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run 
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\97254\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run 
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\97254\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\97254\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 287, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "c:\Users\97254\Documents\Programing\dagger\test.py", line 12, in test
    async with dagger.Connection(config) as client:
  File "C:\Users\97254\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagger\connection.py", line 39, in __aenter__
    return await self.connector.connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\97254\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagger\connectors\docker.py", line 168, in connect
    await anyio.to_thread.run_sync(self.provision_sync)
  File "C:\Users\97254\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\97254\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\97254\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagger\connectors\docker.py", line 61, in start    os_, arch = get_platform()
                ^^^^^^^^^^^^^^
  File "C:\Users\97254\AppData\Local\Programs\Python\Python311\Lib\site-packages\dagger\connectors\docker.py", line 26, in get_platform    uname = os.uname()
            ^^^^^^^^
AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?

### Steps to reproduce

`pip install dagger-io`

and run the [snippet](https://docs.dagger.io/sdk/python/628797/get-started#step-2-create-a-dagger-client-in-python) from the documentation:

```
"""
Execute a command
"""

import sys
import anyio
import dagger

async def test():
    config = dagger.Config(log_output=sys.stderr)

    async with dagger.Connection(config) as client:

        python = (
            client.container()

            # pull container
            .from_("python:3.10-slim-buster")

            # get Python version
            .exec(["python", "-V"])
        )

        # execute
        version = await python.stdout().contents()

        print(f"Hello from Dagger and {version}")

if __name__ == "__main__":
    anyio.run(test)
```

### Dagger version

0.1.1 (dagger-io python client version)

### OS version

Windows 11

**Comment by noamisraeli** [comment] 2022-11-20 09:54
After viewing the place in the code where the exception was raised from, it looks like it was fixed in the latest version of this repo, but it is not yet published to the PyPI.

**Comment by helderco** [comment] 2022-11-20 14:13
Duplicate of #3813

**Comment by helderco** [comment] 2022-11-20 14:14
A release is coming soon early this week.

**Closed by helderco** 2022-11-20 14:13 UTC
