### ISSUE TITLE
Changing client filesystem read path from "." to "./" triggers cyclic task dependency error

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#1857] opened 2022-03-25 11:26 UTC
This was discovered while trying to make the todoapp example config clearer:

```diff
diff --git a/pkg/universe.dagger.io/examples/todoapp/netlify.cue b/pkg/universe.dagger.io/examples/todoapp/netlify.cue
index 0c5cda96..d52be0c5 100644
--- a/pkg/universe.dagger.io/examples/todoapp/netlify.cue
+++ b/pkg/universe.dagger.io/examples/todoapp/netlify.cue
@@ -19,7 +19,7 @@ dagger.#Plan & {
        }
        client: {
                filesystem: {
-                       ".": read: {
+                       "./": read: {
                                contents: dagger.#FS
                                exclude: [
                                        "README.md",
@@ -28,7 +28,7 @@ dagger.#Plan & {
                                        "node_modules",
                                ]
                        }
-                       build: write: contents: actions.build.contents.output
+                       "./build": write: contents: actions.build.contents.output
                }
                env: {
                        APP_NAME:      string
```

Tested with `v0.2.2` on Linux:

```console
❯ dagger version
dagger 0.2.2 (fead547d) linux/amd64

❯ dagger do build
11:23AM FTL failed to execute plan: cyclic task dependency:
        task client.filesystem."./build".write refers to
        task actions.build.contents._copy refers to
        task actions.build.run._exec refers to
        task actions.test._exec refers to
        task actions.deps._dag."2"._exec refers to
        task actions.deps._dag."1"._copy refers to
        task client.filesystem."./build".write:
    /home/gerhard/github.com/gerhard/dagger/pkg/universe.dagger.io/cue.mod/pkg/dagger.io/dagger/fs.cue:114:2
    /home/gerhard/github.com/gerhard/dagger/pkg/universe.dagger.io/docker/build.cue:49:2
    /home/gerhard/github.com/gerhard/dagger/pkg/universe.dagger.io/docker/run.cue:162:2
```

**Comment by helderco** [comment] 2022-03-31 21:30
Tracked in https://github.com/dagger/dagger/issues/493

**Comment by helderco** [comment] 2022-04-29 17:27
Duplicate of https://github.com/dagger/dagger/issues/1885

Even though this issue came first, the other one captures the core of the issue. This cycle is because of a dependency to an empty/ignored action. When that issue's resolved, this one will be as well.

**Closed by helderco** 2022-04-29 17:27 UTC
