### ISSUE TITLE
#DockerBuild.platforms seems to be non-functioning

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [dagger/dagger#437] opened 2021-05-10 01:37 UTC
```
package cake

import (
	"dagger.io/dagger/op"
)

mybuild: #up: [
	op.#DockerBuild & {
		dockerfile: """
		FROM debian
		"""
		platforms: ["linux/amd64", "linux/arm64"]
	},
]

```

```
6:22PM FTL system | failed to up environment: buildkit solve: task failed: invalid map result
```

Buildkitd output the same (unhelpful) message:

```
ERRO[0010] /moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = task failed: invalid map result
```

This works fine with a single platform being listed.

**Comment by jpadams** [comment] 2022-06-26 21:13
Seems like the issue is here:
https://github.com/dagger/dagger/blob/main/solver/solver.go#L117-L132
which was inspired by
https://github.com/moby/buildkit/blob/master/frontend/dockerfile/dockerfile2llb/convert.go
which seems to have added quite a bit of multi-arch support since January 2022
https://github.com/moby/buildkit/commits/master/frontend/dockerfile/dockerfile2llb/convert.go

**Comment by shykes** [comment] 2023-01-04 18:58
Closing this, since 1) the CUE SDK does not support multi-platform, 2) @dubo-dubon-duponey is no longer actively using the CUE SDK, and 3) there is now support for multi-platform in the new GraphQL API: see [`Container { withPlatform }`](https://docs.dagger.io/api/reference/#definition-Container).

**Closed by shykes** 2023-01-04 18:58 UTC
Labels: kind/bug, kind/user-request, sdk/cue
