### ISSUE TITLE
🐞 Dagger CLI v0.8.X hangs when running targets

### ISSUE THREAD

**Issue by alexandreLamarre** [dagger/dagger#5618] opened 2023-08-11 16:18 UTC
### What is the issue?

Any dagger target run through the CLI results in a hang for example:

```
dagger run go run ./dagger --charts.git.export
```
but the same command 
```
go run ./dagger --charts.git.export
```
completes no problem. Also using CLI version v0.6.4 works no problem.

## Versions 
- dagger engine v0.8.1 
- dagger CLI v0.8.1 (2b855693b080a996bd0be19826754984684dd145), built from source `CGO_ENABLED=0 go install ./cmd/dagger`

<details>
<summary> Docker info </summary>
<pre><code>
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /home/alex/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /home/alex/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.20.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.31GiB
 Name: docker-desktop
 ID: e23414a8-e8bf-47ad-b06e-7ea4345e83aa
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
</pre></code>
</details>

### Log output

 ```
 dagger run go run ./dagger --charts.git.export
• Engine: github.com/moby/buildkit (version v0.0.0+unknown)
Error: connect: context canceled
```
logs appear only after sending a siginterrupt

### Steps to reproduce

`example/go.mod`
```
module example.com

go 1.21.0

require (
	dagger.io/dagger v0.8.1
)

```

`example/main.go`
```go
package main

import (
	"context"
	"fmt"
	"os"

	"dagger.io/dagger"
)

func main() {
	if err := build(context.Background()); err != nil {
		fmt.Println(err)
	}
}

func build(ctx context.Context) error {
	fmt.Println("Building with Dagger")

	// initialize Dagger client
	client, err := dagger.Connect(ctx, dagger.WithLogOutput(os.Stderr))
	if err != nil {
		return err
	}
	defer client.Close()

	return nil
}

```

Use CLI version v0.8.1

```bash
dagger run go run./example
```

### SDK version

go 1.21

### OS version

Ubuntu22.0.4

**Comment by alexandreLamarre** [comment] 2023-08-11 17:06
@helderco  yes my bad, `dagger do` was the wrong commad, however `dagger run go run ./dagger --charts.git.export` runs into the exact same hang

**Comment by helderco** [comment] 2023-08-11 19:33
Can you make a simple reproducible example?

**Comment by alexandreLamarre** [comment] 2023-08-11 21:00
I've edited the steps to reproduce from `dagger do` to `dagger run `

**Comment by helderco** [comment] 2023-08-11 23:02
If you're hanging with what's in the description then there must be something not quite right with your environment. Try to isolate as much as possible and provide exact steps to reproduce.

For how long does it hang for you? Have you tried restarting docker or pruning the cache? Without knowing more it's hard to tell.

**Comment by gerhard** [comment] 2023-08-12 15:38
On a [Digital Ocean `c-4-intel`](https://slugs.do-api.dev/) running Ubuntu 22.04 I installed [Docker v24.0.5](https://docs.docker.com/engine/install/ubuntu/) & [Go v1.21.0](https://go.dev/doc/install).

<details>
<summary><code>docker info</code></summary>
<pre><code>
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-78-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.751GiB
 Name: ubuntu-c-4-intel-nyc1-01
 ID: 58c67846-6ae1-4940-aba4-a1d695bef356
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
</pre></code>
</details>

I installed `dagger`:
```shell
cd /usr/local
curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.8.1 sh

which dagger
# /usr/local/bin/dagger

dagger version
# dagger v0.8.1 linux/amd64
```

I then re-created your setup:
```go
cd ~
mkdir dagger-issue-5168
cd !$

go mod init !$
go get dagger.io/dagger@v0.8.1

cat > main.go <<EOF
package main

import (
	"context"
	"fmt"
	"os"

	"dagger.io/dagger"
)

func main() {
	if err := build(context.Background()); err != nil {
		fmt.Println(err)
	}
}

func build(ctx context.Context) error {
	fmt.Println("Building with Dagger")

	// initialize Dagger client
	client, err := dagger.Connect(ctx, dagger.WithLogOutput(os.Stderr))
	if err != nil {
		return err
	}
	defer client.Close()

	return nil
}
EOF
```

And finally ran `dagger run go run main.go` **from within** `~/dagger-issue-5168`:

https://github.com/dagger/dagger/assets/3342/47902331-300a-4d4c-96f3-3cfb629d45a8

You can tell that the above was the first run since it took longer to set everything up.

BTW, if you want to see more details as to what is happening, try running with `dagger run --debug`:

https://github.com/dagger/dagger/assets/3342/2858183e-80f6-4257-84c1-8198304bce32

I share @helderco's suspicion, there must be something different about your setup.

**Comment by alexandreLamarre** [comment] 2023-08-12 17:23
@gerhard I appreciate you taking a look.

I am running it on WSL `Kernel Version: 5.15.90.1-microsoft-standard-WSL2` as in the docker info above, and I have run with `--debug` with the same result. Our other team members have been running into this on mac environments as well

The failure is likely induced by an upstream `moby:buildkit` issue or something along those lines, however downgrading to dagger CLI v0.6.4 works as expected -- which is why I opened the issue here

 when I have a moment I'll try and narrow down the root cause

**Comment by alexandreLamarre** [comment] 2023-08-19 18:59
Upgrading to v0.8.3 finally yields some DEBUG logs for this issue, using the above repro: 

```
dagger run --debug go run ./
╮
▽ init
█ [5.39s] CANCELED connect
┣ [0.58s] starting engine
┣ [4.74s] starting session
┻
DEBUG: Failed to connect; retrying... error="make request: Post \"http://dagger/query\": net/http: HTTP/1.x transport co
nnection broken: malformed HTTP status code \"*\""
DEBUG: Failed to connect; retrying... error="make request: Post \"http://dagger/query\": net/http: HTTP/1.x transport co
nnection broken: malformed HTTP status code \"*\""
DEBUG: Failed to connect; retrying... error="make request: Post \"http://dagger/query\": net/http: HTTP/1.x transport co
nnection broken: malformed HTTP status code \"*\""
DEBUG: Failed to connect; retrying... error="make request: Post \"http://dagger/query\": net/http: HTTP/1.x transport co
nnection broken: malformed HTTP status code \"*\""
DEBUG: Failed to connect; retrying... error="make request: Post \"http://dagger/query\": net/http: HTTP/1.x transport co
nnection broken: malformed HTTP status code \"*\""
• Engine: github.com/moby/buildkit (version v0.0.0+unknown)
⧗ 5.39s  ✔ 1
run canceled
```

**Comment by kepi** [comment] 2023-08-22 19:20
I'm not 100 % sure that I had same issue, but dagger 0.8.1 was stuck on my basic quickstart pipeline. Didn't react to quit (`q`) and had to be killed. Btw. engine container hasn't been started at all when it was stuck.

With 0.8.4 it works OK.

**Comment by alexandreLamarre** [comment] 2023-08-22 20:54
looks like 0.8.4 has fixed the issue for me as well

**Comment by alexandreLamarre** [comment] 2023-08-22 21:00
with 0.8.4 I'm stilling hitting the malformed http status response code
```
dagger run --debug go run ./
╮
▽ init
█ [2.79s] CANCELED connect
┣ [0.64s] starting engine
┣ [2.07s] starting session
┻
DEBUG: Failed to connect; retrying... error="make request: Post \"http://dagger/query\": net/http: HTTP/1.x transport co
nnection broken: malformed HTTP status code \"*\""
DEBUG: Failed to connect; retrying... error="make request: Post \"http://dagger/query\": net/http: HTTP/1.x transport co
nnection broken: malformed HTTP status code \"*\""
DEBUG: Failed to connect; retrying... error="make request: Post \"http://dagger/query\": net/http: HTTP/1.x transport co
nnection broken: malformed HTTP status code \"*\""
DEBUG: Failed to connect; retrying... error="make request: Post \"http://dagger/query\": net/http: HTTP/1.x transport co
nnection broken: malformed HTTP status code \"*\""
• Engine: github.com/moby/buildkit (version v0.0.0+unknown)
⧗ 2.79s  ✔ 1
run canceled
```

**Comment by gerhard** [comment] 2023-08-30 18:32
That output suggests to me that there is a version mismatch between the CLI, SDK & Engine.

This line is most suspicious: `• Engine: github.com/moby/buildkit (version v0.0.0+unknown`

Ensure that:
- `dagger version` output contains `v0.8.4`
- `dagger query <<< '{ container { from(address:"hello-world") { stdout } } }'` output contains `v0.8.4` & returns a success code

This is what a successful output should look like:
![Screenshot 2023-08-30 at 19 30 37](https://github.com/dagger/dagger/assets/3342/fc8c166e-a407-461a-aae2-d94dab2b5206)

Can you share your output @alexandreLamarre?

**Comment by gerhard** [comment] 2023-09-13 10:53
I'm closing this since:
- we were unable to reproduce on [a clean Ubuntu 22.04 install with Docker v24.0.5 & Go v1.21.0](https://github.com/dagger/dagger/issues/5618#issuecomment-1675967940)
- this seems like a CLI, SDK & Engine version mismatch issue, but we are unable to confirm

If you are able to share more details that will help us reproduce @alexandreLamarre, please re-open.

Thank you!

**Closed by gerhard** 2023-09-13 10:53 UTC
