### ISSUE TITLE
When using Dagger interactively, feedback about what is happening could reduce confusion.

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#4820] opened 2023-03-23 14:20 UTC
From user:

> There's also a DX issue in that there's nothing in the logs that's telling you what dagger is doing. It just look like it hangs. I get half a gigabit so the delay in feedback only lasts a few seconds at most, but for my colleague it was a minute + of nothing and then 💥. Try throttling your download speed to something uber low and you'll see what I mean

I have a hypothesis (now confirmed a bit ☝️) that lack of feedback for multi-second spans of time is confusing for users and that they'd benefit from feedback like

```
Dagger Engine downloading...
Dagger Engine starting...
...
```

```
Existing Dagger Engine found...
...
```

**Comment by grouville** [comment] 2023-04-17 15:50
@helderco has already implemented a progress spinner in the Python SDK: 

![Image](https://user-images.githubusercontent.com/31691250/232540906-5ebbfb3d-6586-48c0-9db8-33b60be0a34c.png)

Making it available on all SDKs would be a first step towards a better DX. WDYT @helderco ?

**Comment by helderco** [comment] 2023-04-17 20:35
That spinner isn't implemented by the Python SDK, it's just using a third-party library: [rich](https://rich.readthedocs.io). Like Mage (Go) and Typer (Python) on making an entrypoint, every SDK would need to come up with their own solution.

So the _rich_ example shown can be used for progress during provisioning (which doesn't happen with `dagger run`), and it can be improved. However to include also progress from the engine, we would need structured logging.

This has been reported here (not specific to Python actually, it could be generalized):
- https://github.com/dagger/dagger/issues/4186

However let's see if `dagger run` can be good enough for this.

**Comment by gerhard** [comment] 2023-05-16 15:14
As a short-term solution, we should print the lines that @jpadams is suggesting in all SDKs. When entrypoints / `dagger run` lands, this will not be a problem anymore, but from the perspective of a small improvement, this is still worth doing.

**Comment by helderco** [comment] 2023-07-28 10:46
> As a short-term solution, we should print the lines that @jpadams is suggesting in all SDKs. When entrypoints / `dagger run` lands, this will not be a problem anymore, but from the perspective of a small improvement, this is still worth doing.

When running with the CLI, you already have early feedback with Progrock (`dagger run`, Zenith, etc...). The lack of early feedback comes from using automatic provisioning in the SDKs. So I'd say https://github.com/dagger/dagger/pull/5488 isn't just a short-term solution, it's a fix for this issue.

Additionally, this is actually a duplicate of https://github.com/dagger/dagger/issues/4456 so we should close this one, and link the PR to the earlier one.

**Comment by TomChv** [comment] 2023-07-28 10:51
@helderco The PR is ready btw, if you to merge the fix :)

**Comment by helderco** [comment] 2023-07-31 12:28
@jpadams can you confirm that these solve this issue?
- #5488 
- #5522

**Comment by TomChv** [comment] 2023-08-18 12:28
@jpadams  I'm closing this issue for now since we add nice improvement to the logging, feel free to reopen it if you have new suggestions of logging 🚀

**Closed by TomChv** 2023-08-18 12:28 UTC
Labels: kind/dx, kind/user-request, CI+
