### ISSUE TITLE
Document core.#Source: what is it for, how do I use it?

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2467] opened 2022-05-17 22:47 UTC
`core.#Source` is an important feature of the Dagger API, and it is not documented anywhere.

As requested by @siafu: "it would be great if you could explain when to use `core.#Source` versus `client.filesystem`.

**Comment by samalba** [comment] 2022-05-19 00:22
Closing, duplicate of #2342

**Closed by samalba** 2022-05-19 00:22 UTC
Labels: area/documentation, kind/user-request
