### ISSUE TITLE
🐞 Fail to set InstallPath on Windows

### ISSUE THREAD

**Issue by 18183883296** [dagger/dagger#7035] opened 2024-04-06 02:22 UTC
### What is the issue?

Fail to set InstallPath on Windows with PowerShell v7.4.1

### Dagger version

dagger v0.11.0

### Steps to reproduce

```
$script = Invoke-WebRequest -UseBasicParsing -Uri https://dl.dagger.io/dagger/install.ps1
$params = "-InstallPath A:\dagger"
"$script $params" | Invoke-Expression
```

### Log output

```
-InstallPath:
Line |
  78 |   -InstallPath A:\dagger
     |   ~~~~~~~~~~~~
     | The term '-InstallPath' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jedevc** [comment] 2024-04-08 10:49
Going to mark this as a dupe of #6901 - it's part of a more general issue that the windows installation instructions are very not up-to-date.

I've added the other one to an upcoming milestone, hopefully we can have a better experience on windows for the next release :tada:

**Closed by jedevc** 2024-04-08 10:49 UTC
