### ISSUE TITLE
🐞 v0.15.0 break the pipeline both in local and in github actions 

### ISSUE THREAD

**Issue by bastid3v** [dagger/dagger#9177] opened 2024-12-12 14:06 UTC
### What is the issue?

Dagger was in `latest` on our CI and I realized today that the CIs no longer pass while they passed 2 days ago. 

The only variable different between these 2 days is the release of `v0.15.0`.

So I immediately installed the latter. And indeed it crashes locally too.

So I fixed in `v0.14.0` on our CI for the moment.

I did not expect that a minor version could break everything and I hope that it is me who did something wrong.

There are no commands related to the module that seem to work.

`dagger functions` - doesn't work
`dagger call <any-function>` - doesn't work 

### Dagger version

dagger v0.15.0 (registry.dagger.io/engine:v0.15.0) darwin/arm64 (did the same errors on github actions)

### Steps to reproduce

To be honest, I don't know which information would be useful to give you since I didn't succeed in reproducing this issue. **Don't hesitate to ask for any further information to help with this.**

We have a `bun` repository that uses Dagger with its default package manager, which seems to be `yarn`. Bun is at version `1.1.36`, and I'm using Node version `22.11.0`.

I saw that there's an experimental `bun` runtime to specify in Dagger's `package.json`, but it didn't solve the issue either.

Dagger is set up with the `typescript` SDK.

Here are our package files that might be useful:
```sh
❯ tree -L1
.
├── README.md
├── asserter
├── biome.json
├── build.ts
├── bun.lockb
├── common
├── dagger
├── dagger.json
├── docs
├── grapher
├── node_modules
├── package.json
├── profiler
├── test-utils
├── tsconfig.bun.json
├── tsconfig.json
└── typedoc.json

❯ cd dagger
❯ tree -L1
.
├── package.json
├── sdk
├── src
├── tsconfig.json
└── yarn.lock

❯ cd sdk/src
❯ tree -L1
.
├── api
├── common
├── connect.ts
├── connectOpts.ts
├── index.ts
├── module
└── telemetry
```

There is only one file `index.ts` under `dagger/src/index.ts`.

Here is dagger's config files:
`dagger.json`:
```json
{
  "name": "dragee-model",
  "engineVersion": "v0.15.0",
  "sdk": "typescript",
  "source": "dagger"
}
```

`dagger/tsconfig.json`
```
{
  "compilerOptions": {
    "target": "ES2022",
    "moduleResolution": "Node",
    "experimentalDecorators": true,
    "paths": {
      "@dagger.io/dagger": [
        "./sdk/src"
      ],
      "@dagger.io/dagger/telemetry": [
        "./sdk/src/telemetry"
      ]
    }
  }
}
```

`dagger/package.json`
```json
{
    "type": "module",
    "dependencies": {
        "@dagger.io/dagger": "./sdk",
        "typescript": "^5.5.4"
    },
    "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
}
```

### Log output

Here is the log that fail on the CI with every informations
[0_Check PR's lint and tests.txt](https://github.com/user-attachments/files/18112746/0_Check.PR.s.lint.and.tests.txt)

**Comment by jedevc** [comment] 2024-12-12 17:29
Hm, in your logs it looks like we have:

```
IntrospectionError: could not resolve type reference for any.                                                  
    at DaggerModule.resolveReferences (/src/dagger/sdk/src/module/introspector/dagger_module/module.ts:242:13) 
    at new DaggerModule (/src/dagger/sdk/src/module/introspector/dagger_module/module.ts:114:10)               
    at scan (/src/dagger/sdk/src/module/introspector/index.ts:18:18)                                           
    at async connection.LogOutput (/src/dagger/sdk/src/module/entrypoint/entrypoint.ts:17:26)                  
    at async <anonymous> (/src/dagger/sdk/src/connect.ts:44:11)                                                
    at async withGQLClient (/src/dagger/sdk/src/common/graphql/connect.ts:24:12)                               
    at async <anonymous> (/src/dagger/sdk/src/connect.ts:40:9)                                                 
    at async connection (/src/dagger/sdk/src/connect.ts:38:5)                                                  
    at async entrypoint (/src/dagger/sdk/src/module/entrypoint/entrypoint.ts:11:3) {                           
  cause: undefined,                                                                                            
  code: 'D110'                                                                                                 
}                                                                                                              
```

That feels like a moderate issue :laughing: cc @TomChv 

> I did not expect that a minor version could break everything and I hope that it is me who did something wrong.

Generally, we try and keep breaking changes to a minimum (and this definitely looks like a bug), but it's not always 100% possible. Before v1.0, semver doesn't have the same requirements post v1.0 - because dagger is a relatively new piece of software, we still need the freedom to iterate quickly, though we're doing our best to avoid breaking things unnecessarily.

**Comment by TomChv** [comment] 2024-12-12 17:48
@bastid3v Thanks for a lot for this detailed issue.

This new behaviour is introduced by #8824 and is cause by a type used in a Dagger function that isn't supported.
The PR I mentioned above improve the overall type resolution of a module, and specially catch unresolved value so it's an intended behaviour and actually fixes a bug where unresolved type where ignored. 

I'm sorry that it actually broke your module ☹️.

According to the error:

```shell
IntrospectionError: could not resolve type reference for any
```

There's a dagger function or property in your code that uses the type `any`, which is not supported by Dagger and it might have been ignored before by the TS SDK (meaning that the module was relying on a non-exact introspection).

If you can share the module's code or some simple representation of the function's signatures, that would really help me to debug you.
You can tag me on discord @vasek.technology if you don't want to share the code publicly.

**Comment by TomChv** [comment] 2024-12-13 10:43
> I've basically let the types be inferred, but maybe I should specify the return type for every function?
> Please let me know if I'm doing something wrong or if there's anything I can improve 🙌

Oh yeah that's it! You should always explicitly type function that are exposed to the Dagger API (return type, args, props etc...)
Otherwise the runtime isn't able to correctly guess the return type.

Before I wasn't strictly check the return type introspection and this could lead to some issues so now it's strictly checked.

If your function isn't decorated with `@func()` you can let the compiler infer since it's not introspected but otherwise you should :D

So there's no bug, it's just that the code was wrong before but the introspector wasn't veriying that, now it does :)

Thanks a lot for sharing your module! Is there something in our doc (https://docs.dagger.io) that we could add to avoid this little mistake?

**Comment by TomChv** [comment] 2024-12-13 15:45
> Okay, I've specified the return type for every function, and it seems to have resolved the introspection error.

Amazing! I'm gonna close this issue then 🚀 

> Yes! I think it's worth mentioning. I tend to let functions infer their return types, and others might be doing the same. It’d help you avoid these kinds of issues :)
I guess I would like to find it [here](https://docs.dagger.io/api/sdk) ? But I definitely think it's important to mention.

Yup, also here might be good: https://docs.dagger.io/api/custom-functions, wdyt @vikram-dagger ?

**Closed as completed by TomChv** 2024-12-13 15:45 UTC
Labels: area/sdk/typescript
