### ISSUE TITLE
Add this comment and `update`+`do` pattern to all CI examples?

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2282] opened 2022-04-22 21:15 UTC
### What is the issue?

Should we add this comment and `update`+`do` pattern to all CI examples as a best practice until more package/dependency management changes land?

https://github.com/dagger/dagger/blob/main/.github/workflows/todoapp.yml#L75-L78

**Comment by helderco** [comment] 2022-05-06 22:52
Duplicate of #2315

I know that came later but it has more content.

**Closed** 2022-05-06 22:55 UTC
Labels: area/documentation, resolution/duplicate, ecosystem
