### ISSUE TITLE
Run only split test suite in PRs

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#8546] opened 2024-09-23 16:06 UTC
## Problem

Our test suite is slow and unreliable. While we fix that, we have created a split version of the same test suite, that can run on multiple machines. The split version is considerably faster and more reliable.

But we still run both versions of the test suite on each PR. As a result PRs still suffer from long check time, and frequent flakes.

There is a valid reason for continuing to run the slow test suite: fresh data for "flake hunting". But our contribution experience is paying too high a price for that fresh data.

## Solution

Find another way to collect fresh data for flake hunting, while allowing contributors to benefit from the faster split test suite.

My suggestion:

- Run only the split test suite on PRs
- Run the split / non-split combination side-by-side out of band: either N times per day, or on push to main. Anything as long as it's not on PR.

**Comment by shykes** [comment] 2024-09-23 16:07
As discussed with @gerhard @matipan @jedevc @kpenfound 

@sipsma your opinion was keenly requested

**Comment by sipsma** [comment] 2024-09-23 18:51
>  The split version is considerably faster and more reliable.

Is it still considerably more reliable? The last time @gerhard shared metrics was the team meeting on Thursday, when the reliability was 60% (no split) vs 75% (split), which is relatively close given the noise involved here. And later that day https://github.com/dagger/dagger/pull/8470 was merged, which trimmed another huge chunk of test flake occurrences.

Looking at CI **test** workflows (ignoring other infra problems like spot instance cancelation, macos runner failing, external service bugs outside our control) on main from the one up to the most recent:
1. ✅ https://github.com/dagger/dagger/commit/0cae0be33f7c7b68871fb331ec1572cfafe4d1e8
2. ❌ https://github.com/dagger/dagger/commit/d8a7f5650fd34045bdbbf0575820f7015c9984bc
   * 1 **split test** failure https://dagger.cloud/dagger/traces/1d99da422fdc9a4f61d2903c3d2eae72
3. ✅ https://github.com/dagger/dagger/commit/f15c2996d26dbbc17bec4b6377629bdf1e934ddf
3. ✅ https://github.com/dagger/dagger/commit/1ced6594b53688311389d1388a2819ddc77b4695
4. https://github.com/dagger/dagger/commit/37182a86609bfb14eb24b17229b1085d95c5cca2
   * [Only failure](https://github.com/dagger/dagger/actions/runs/10961588283/job/30438867922) ([traces](https://dagger.cloud/dagger/traces/6396fba9fb2f11272cc2c2f2781e28ad?span=aa6848d845aae4d0#8c1bfc4698fd3a32)) was due to [upstream go module proxy infra problem](https://github.com/golang/go/issues/69544), which has been fixed by them, nothing to do with us
5. ✅ https://github.com/dagger/dagger/commit/576d437da1cacd2ea15d502590878bb00795b8e4
6. ❌https://github.com/dagger/dagger/commit/4fcf5efdf0927883e5fd58d789b9a969471acff5
   * 1 **combined test** failure (https://dagger.cloud/dagger/traces/aa0c05d27e1f539f743f501368d4126d) 
   * 1 **split test** failure (https://dagger.cloud/dagger/traces/aeb8bebe5a1102a53a7fc3674ae6e993
     * A second split test failure appears to have been the same [upstream go module proxy infra problem](https://github.com/golang/go/issues/69544) mentioned above, not related to us
8. ✅ https://github.com/dagger/dagger/commit/d3a02170c96d4d81343dbbcd5c555ba6b8d38b45
9. ✅ https://github.com/dagger/dagger/commit/5ec03a604d50b721aaa65ba7c4db8c875696ac72
10. https://github.com/dagger/dagger/commit/36cfba5b1cd75c7b672471167f0dee4b9942788c
    * Only **combined test** failure was a 500 error returned by yarn package index, not an engine bug https://dagger.cloud/dagger/traces/fb558c678d06ec086c2331a279d95c4e
    * Many **split tests** are stuck in Queued, have not run so no data https://github.com/dagger/dagger/actions/runs/10993033773/job/30518658241
11. ❌ https://github.com/dagger/dagger/commit/05cc202bce305b56841fa78bb519a52f5515e8f5
    * 1 **combined test** failure https://dagger.cloud/dagger/traces/01072eb69a45d3afbe0307ae199eb0a6
    * Many **split tests** are stuck in Queued, have not run so no data https://github.com/dagger/dagger/actions/runs/10996802998/job/30530826306

In total, including workflows where a bunch of the split tests got stuck in Queued due to some infra problem and thus don't have a pass/fail status yet:
1. 2 **combined test** failures
2. 2 **split test** failures, with a bunch of data missing due to aforementioned Queued jobs problem

---

Also in terms of performance, it makes perfect sense that parallelizing the jobs across many more CPUs+Disks (which is what the split tests do) reduces the wall-clock runtime.

The thing is, the wall-clock time doesn't appear to be linear with the underlying infra size and actually suggests that combining may be more efficient? Please double check everything here, there's a lot of details and I could be missing something important.

For example, on [this recent commit](https://github.com/dagger/dagger/commit/5ec03a604d50b721aaa65ba7c4db8c875696ac72) where all tests succeeded:
* [Split tests](https://github.com/dagger/dagger/actions/runs/10973276800/job/30470480363) (not including **dev**)
   * `test-modules` - 7m13s - 16core runner
   * `test-modules-runtime` - 8m26s - 16core runner
   * `test-cli-engine` - 4m31s - 16core runner
   * `test-everything-else` - 9m8s - 16core runner
   * **TOTAL (not including parallelism of jobs)**: (29m 18s / 64cores) = 27.4 s/core
* [Combined tests](https://github.com/dagger/dagger/actions/runs/10973276805/job/30470480111) (not including **dev**)
  * `test` - 18m48s - 16core runner
  * **TOTAL (not including parallelism of jobs)**: (18m48s / 16cores) = 70.5 s/core

So, in the combined tests, we get ~2.6x work out of each core in terms of total wall clock time spent per core, which is much more efficient.

What this suggests, and could easily be proven wrong in the real world with some quick testing, is that **increasing the size of the instance we run the unsplit test suite on would be much more efficient** than continuing to run the split test suite.
* Specifically, **we could get the same wall clock runtime as the split tests for less cost** by just increasing the size of the runner of the combined tests

As I said above, there's a million places in the real world where this could diverge (hitting bottlenecks on disk usage where the infra disk bandwidth doesn't scale linearly with the cpu core count). But based on the fact that:
1. The split/unsplit suites don't seem to have much difference in reliability anymore after the various fixes for flakes (which are still being actively worked on too)
2. We *might* be able to get the same total wall clock test suite runtime for a much cheaper infra cost by just increasing the size of the unsplit test suite runner (can be confirmed with testing)

**My suggestion would be to try increasing the size of the runner for combined test suite.** Maybe start by doubling to 32 cores, but as mentioned above the split test suites appear to be parallelizing across 64 cores, so would be fair to get a runner with up to that many too.

If this gets us wall-clock runtime close to or under the wall-clock runtime of the split test suite, I think we should just go with it because it's
1. Cheaper
2. Closer to our end goal in terms of "a single fast workflow that runs all the tests"

**Comment by shykes** [comment] 2024-12-06 23:32
@sipsma @gerhard should I close this?

**Comment by sipsma** [comment] 2024-12-06 23:40
Yeah I'll close, there's more follow up work around the tests but being handled in the engine performance project

**Closed** 2024-12-06 23:41 UTC
Labels: area/ci
