### ISSUE TITLE
🐞 Dagger: runtime: out of memory

### ISSUE THREAD

**Issue by lyzhang1999** [dagger/dagger#1955] opened 2022-03-31 07:24 UTC
### What is the issue?

I have written some of my own CUE Modules, which may go out of memory when run multiple times over a long period of time.

### Log output

![飞书20220331-151758](https://user-images.githubusercontent.com/8142348/161000449-503f4110-26b0-405a-99cd-c89a3b56535c.png)

### Dagger version

dagger devel (b32c8732) linux/amd64

### OS version

Linux VM-0-6-ubuntu 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by grouville** [comment] 2022-03-31 13:06
Hello,
Thanks for the issue. Can you please paste your docker Resources info ? My instinct tells me that you go out of memory in the docker daemon scope
<img width="612" alt="image" src="https://user-images.githubusercontent.com/31691250/161061662-eb3b98c2-8eb5-4f9d-b3e7-7e61bce1d566.png">

**Comment by grouville** [comment] 2022-03-31 14:32
> . when I upgrade dagger 0.2 and migrate some cue module to 0.2 API, sometimes it happen. and when I use Dagger 0.2, It see

Ok. We'll need access to a repro case (even privately) in order to isolate the root cause. Could you please send us a `Gist` ?

>  It seem calculating DAG becomes very slow
Do you mean with a `cue eval` ?

**Comment by lyzhang1999** [comment] 2022-04-01 07:05
![20220401-150312](https://user-images.githubusercontent.com/8142348/161212401-5731a7be-c77e-4379-ae72-990a62dd9cf8.png)

I'll provide another clue and we can discuss the repository access issue later.

**Comment by jlongtine** [comment] 2022-04-01 17:20
I could be wrong, but this sounds like a CUE evaluation issue. There are some cases that cause the CUE evaluator to blow up and chew through RAM. I agree with @grouville about creating a repro (including looking at the actual CUE causing this -- privately) and figuring out what is going on. 

@grouville Feel free to pull me in, if you're getting stumped on this. 

One thing to try: `cue eval` the config. That should help us narrow it down.

**Comment by grouville** [comment] 2022-04-01 17:27
> looking

Yes with pleasure @jlongtine. I'm currently waiting for their repro case, but will totally and confidentially share it with you 😇 

> I could be wrong, but this sounds like a CUE evaluation issue
That's what I thought yes. Let's see whenever it's ready 😇

**Comment by lyzhang1999** [comment] 2022-04-11 06:55
have we got any new information?

**Comment by captainroy-hy** [comment] 2022-04-11 07:10
> have we got any new information?
I think it's related to this [issue](https://github.com/cue-lang/cue/issues/1418)

**Comment by lyzhang1999** [comment] 2022-04-11 12:27
> > have we got any new information?
> 
> maybe it's related to this [issue](https://github.com/cue-lang/cue/issues/1418) It was involved in v0.3.0-alpha4 and has been [fixed](https://github.com/cue-lang/cue/commit/195cdf7e74e4b633419f2fa2a605bd932f9889aa) in v0.4.3-beta.1.

thanks, but I tried to upgrade dagger cue module to v0.4.3-beta.2, the problem still exist.

**Comment by TomChv** [comment] 2023-10-30 19:05
Hey @lyzhang1999 It's been a long time you opened this issue!

Did you had the occasion to try our new dagger version and see if you still hit that issue?
You can onboard on our new version by following the documentation:  https://docs.dagger.io/quickstart

Let me know if you have this problem again, if not I can close this issue 🚀

**Comment by helderco** [comment] 2024-01-18 13:19
Closing since [CUE is no longer supported](https://dagger.io/blog/ending-cue-support).

**Closed by helderco** 2024-01-18 13:19 UTC
Labels: kind/bug, kind/user-request, sdk/cue
