### ISSUE TITLE
Secrets from cloud secret manager

### ISSUE THREAD

**Issue by mrgleeco** [dagger/dagger#2377] opened 2022-04-29 19:18 UTC
### What are you trying to do?

Ideally dagger can support secrets found in a secret manager, eg. [GCP secret manager](https://cloud.google.com/secret-manager/docs) or [AWS](https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html)

Perhaps this exists(?) and i am just seeking docs...

**Comment by TomChv** [comment] 2022-07-11 17:35
It actually does, we already have a type named `dagger.#Secret` that can store secret.

See [dagger secrets docs](https://docs.dagger.io/1204/secrets/#what-are-secrets) for more information.

**Comment by samalba** [comment] 2023-01-10 00:14
Duplicate of #2377

**Closed by samalba** 2023-01-10 00:14 UTC

**Comment by marcindulak** [comment] 2023-01-10 06:21
This issue is 2377. Which is the duplicate?

**Comment by samalba** [comment] 2023-01-11 18:52
> This issue is 2377. Which is the duplicate?

🤦 sorry my bad...

I meant Duplicate of #4339

**Comment by samalba** [comment] 2023-01-11 18:53
Duplicate of #4339
