### ISSUE TITLE
🐞 Cue function regexp.ReplaceAll not working

### ISSUE THREAD

**Issue by akselleirv** [dagger/dagger#2982] opened 2022-08-29 12:18 UTC
### What is the issue?

Using `regexp.ReplaceAll` is not working.

### Log output

`invalid interpolation: cannot call non-function regexp.ReplaceAll (type _|_)`

### Steps to reproduce

```
package main

import (
	"regexp"
	"dagger.io/dagger"
	"universe.dagger.io/bash"
)

dagger.#Plan & {
	actions: test: {
		src:        "# Something ---!"
		regex:      "# Something"
		replaceStr: "# Updated!"
		result:     regexp.ReplaceAll(regex, src, replaceStr)
		run:        bash.#RunSimple & {
			script: contents: "echo \(result)"
		}
	}
}
```

Using the function in CUE works like expected: https://cuelang.org/play/?id=AEMxTWqqcej#cue@export@cue

### Dagger version

dagger 0.2.31 (8146f4d9a) darwin/arm64

### OS version

macOS 12.5.1

**Comment by slumbering** [comment] 2023-01-17 13:39
cc @jlongtine. Can you reproduce this issue ? Thanks

**Comment by mircubed** [comment] 2023-12-18 19:12
Closing due to end of support for CUE SDK - https://dagger.io/blog/ending-cue-support

**Closed** 2023-12-18 19:12 UTC
Labels: kind/bug, sdk/cue
