### ISSUE TITLE
🐞 website: blog header background don't play well with text content

### ISSUE THREAD

**Issue by proppy** [dagger/dagger#1954] opened 2022-03-31 03:52 UTC
### What is the issue?

I get black text on black background in the blog section which makes it hard to read :)

for example:
- https://dagger.io/blog/public-launch-announcement
![image](https://user-images.githubusercontent.com/5268/160972695-d4797d17-bd69-4c58-9d0a-1da0115f6ded.png)
- https://dagger.io/blog/series-a
![image](https://user-images.githubusercontent.com/5268/160972803-b3451aa5-c200-4e03-9d1a-5d279ad5ac11.png)

Browser:
```
Chrome 100.0.4896.60 (Official Build) (64-bit) 
```

### Log output

N/A

### Steps to reproduce

- navigate to a blog post like thru a direct link like https://dagger.io/blog/public-launch-announcement 

Interestingly it doesn't happen when navigating interactively from the blog section https://dagger.io/blog/ as a header image gets added, see:
![image](https://user-images.githubusercontent.com/5268/160973313-aad7a782-bd7e-463b-b020-558d3d85c191.png)

### Dagger version

N/A

### OS version

Linux proppy 5.15.15-1rodete2-amd64 #1 SMP Debian 5.15.15-1rodete2 (2022-02-23) x86_64 GNU/Linux

**Comment by slumbering** [comment] 2022-03-31 12:52
Hi @proppy . Thanks for your help.
I can't  reproduce this bug. However, I've changed the way images are displayed.
Could you try those following links and tell me if it's better please ? 
https://deploy-preview-165--dagger-io.netlify.app/blog/series-a
https://deploy-preview-165--dagger-io.netlify.app/blog/public-launch-announcement

Thanks :)

**Comment by proppy** [comment] 2022-03-31 15:05
yep better!

![image](https://user-images.githubusercontent.com/5268/161087598-fe28e1d5-d272-4dba-a9d1-4d4322fc8d1c.png)

**Comment by slumbering** [comment] 2022-03-31 15:57
😕 ... still not good... I'm using object-fit css property.
I saw that you are using a Linux distribution, Linux proppy...?

**Comment by gerhard** [comment] 2022-04-01 10:46
I am not seeing this problem on my Chrome Browser running on Linux.

I am testing this on:
- browser: `Google Chrome 99.0.4844.51 (Official Build) (64-bit)`
- OS: `NixOS 21.11`
- kernel: `Linux x22 5.10.103 #1-NixOS SMP Wed Mar 2 10:42:57 UTC 2022 x86_64 GNU/Linux`

This is what navigating directly to https://dagger.io/blog/public-launch-announcement looks like for me:
![image](https://user-images.githubusercontent.com/3342/161247068-53aebeca-1b0d-469a-8e4b-a8c6a07f380b.png)

If the image was slow to load, or maybe not load at all, this is what I would see:
![image](https://user-images.githubusercontent.com/3342/161247677-abc8e4f0-19e0-4543-a4b1-af8db1d253a3.png)

The thing which I find more suspicious is that I was expecting the image to be in an `img` element, but it is in `div src` currently:
![image](https://user-images.githubusercontent.com/3342/161247562-d979e96b-d688-4a95-9fe5-092debd64b8f.png)

Could this be the problem?

I am curious @proppy, does it happen on a different browser too?

---

Another test on Firefox 98.0 & NixOS 21.11:
![image](https://user-images.githubusercontent.com/3342/161248696-a86b38f4-691b-4e86-af53-b9c59a6fae30.png)

And now side-by-side (Chrome is left, Firefox is right):
![image](https://user-images.githubusercontent.com/3342/161248849-5ae73814-6d9c-480e-b810-e3024776e35c.png)

**Comment by slumbering** [comment] 2022-04-01 16:09
thanks @gerhard for your tests. I've actually changed the way this banner is displayed by using a proper <img> tag. https://github.com/dagger/dagger/issues/1954#issuecomment-1084539107

It looks like it improve experience but still not the same result as yours => https://github.com/dagger/dagger/issues/1954#issuecomment-1084720864

**Comment by gerhard** [comment] 2022-04-01 16:55
![image](https://user-images.githubusercontent.com/3342/161308272-4d63443d-c373-44d6-8bb8-d1e887d31332.png)

**Comment by slumbering** [comment] 2022-04-05 18:35
cc @marcosnils :).

**Comment by marcosnils** [comment] 2022-04-05 19:00
:wave: 

just tested in the following browsers in linux and don't have any issues:

`Mozilla Firefox 98.0.2`
`Brave Browser 100.1.37.109`
`Google Chrome 100.0.4896.75 `

**Comment by slumbering** [comment] 2022-04-08 09:34
Ok. So we close this issue as we can't reproduce it.

**Closed by slumbering** 2022-04-08 09:34 UTC
Labels: resolution/wontfix, area/website
