### ISSUE TITLE
🐞 Since v0.11.0 `dagger version` returns a warning when used in a git worktree

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#7089] opened 2024-04-12 19:29 UTC
### What is the issue?

As of `v0.11.0`, when running `dagger version` in a git worktree, it returns a warning:

```console
❯ dagger version
dagger v0.11.0 (registry.dagger.io/engine) darwin/amd64
20:23:06 WRN failed to get repo HEAD err="reference not found"
```

This did not happen before:
- https://github.com/dagger/dagger/pull/6835

```console
❯ dagger version
dagger v0.10.3 (registry.dagger.io/engine) darwin/amd64
```

I do all my development in git worktrees and this is annoying. Just a small papercut, nothing major. Not sure if there is a workaround, but I would be happy to use it if there is one. cc @vito 

### Dagger version

dagger v0.11.0 (registry.dagger.io/engine) darwin/amd64

**Comment by helderco** [comment] 2024-04-12 21:27
Duplicate of https://github.com/dagger/dagger/issues/7030

**Closed by helderco** 2024-04-12 21:27 UTC
Labels: kind/bug
