### ISSUE TITLE
Docs: guides URL

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#4770] opened 2023-03-15 20:25 UTC
For our docs URL schema, we've been using the "knowledge base" model, where each article has a unique ID, allowing decoupling between its content and the overall information architecture. This has proven useful overall.

But I think we have applied this model to certain pages where it doesn't make sense. One example is [our guides section](https://docs.dagger.io/278912/guides). A list of guides is not a knowledge base article, and therefore should not have an article ID embedded in its URL. It would make more sense for that page to be at `https://docs.dagger.io/guides`. This is part of the decoupling I mention above.

There may be other pages where the same observation applies. I haven't checked thoroughly.

**Comment by vikram-dagger** [comment] 2023-03-16 16:20
In principle, I agree and I would nominate the following pages as well:

https://docs.dagger.io/162770/faq -> https://docs.dagger.io/faq
https://docs.dagger.io/648215/quickstart -> https://docs.dagger.io/quickstart
https://docs.dagger.io/[0-9]+/quickstart-* -> https://docs.dagger.io/quickstart-*

However in practice, we have not (yet) defined any rules for when to apply a unique article ID and when not to. So by default, all pages have an auto-generated ID. Happy to spend some time defining this though! As a first cut. maybe the rule is no article IDs for:
- list or index pages eg. /guides
- section "divider" pages eg. /sdk/go, /api
- tightly-linked or dependent groups of pages eg. /quickstart-*

WDYT? It's not very difficult to implement this change as I have already tested and confirmed that Netlify redirects work well for these cases.

I know the genesis of this KB model/architecture is Tailscale docs. I'm not sure it works as well for us though. Tailscale docs seem to refer to a single version of a single product. In our case, we have multiple Dagger versions and also relatively independent sub-components in the SDKs and CLI.

**Comment by shykes** [comment] 2023-03-31 21:57
> However in practice, we have not (yet) defined any rules for when to apply a unique article ID and when not to. So by default, all pages have an auto-generated ID. Happy to spend some time defining this though! As a first cut. maybe the rule is no article IDs for:
> 
> * list or index pages eg. /guides
> * section "divider" pages eg. /sdk/go, /api
> * tightly-linked or dependent groups of pages eg. /quickstart-*
> 
> WDYT? It's not very difficult to implement this change as I have already tested and confirmed that Netlify redirects work well for these cases.

I guess if we can agree one what is "an article" and what is not, then that will give us the rule we're looking for.

> I know the genesis of this KB model/architecture is Tailscale docs. I'm not sure it works as well for us though. Tailscale docs seem to refer to a single version of a single product. In our case, we have multiple Dagger versions and also relatively independent sub-components in the SDKs and CLI.

I trust your instincts as to 1) what the ideal docs model would be for us, and 2) how to get there in a practical way given our current state. Anything you think we should change, now or in the future, is on the table as far as I'm concerned :)

**Comment by mircubed** [comment] 2023-07-20 18:24
@d3rp3tt3 @vikram-dagger can we close this since we are re-thinking a lot of this right now, so it isn't relevant to the upcoming plans?

**Comment by vikram-dagger** [comment] 2023-08-07 19:48
> I don't know what "re-thinking" means, but this is a straightforward problem to fix, and I'm disappointed that it hasn't moved in over 4 months.

Sorry for the wait on this one @shykes. I understood we were discussing significant changes to the docs website structure and navigation (which had potential to impact this) and wanted to see where that landed before modifying the URLs and then possibly needing to update them again. I'll go ahead and make these changes asap.

**Closed** 2023-08-09 07:49 UTC
Labels: area/documentation
