### ISSUE TITLE
✨ Expand File graphql model

### ISSUE THREAD

**Issue by jalvarezit** [dagger/dagger#6970] opened 2024-04-01 08:33 UTC
### What are you trying to do?

I would like to have more detailed data available for the File model, including file permissions and ownership.

### Why is this important to you?

This would allow to add some structure tests for the containers created by dagger similarly to [`container-structure-test`](https://github.com/GoogleContainerTools/container-structure-test).

### How are you currently working around this?

Depending on image binaries like `ls` and `withExec` which may not work in all containers, either because there is no such binary, it has different flags or is a distroless container.

**Comment by helderco** [comment] 2024-04-12 17:51
Duplicate of https://github.com/dagger/dagger/issues/3764

**Closed by helderco** 2024-04-12 17:51 UTC
Labels: User Request, GraphQL API
