### ISSUE TITLE
Remote Projects

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#2165] opened 2022-04-13 01:18 UTC
# Remote Projects

If there's a Dagger project in, say, a git repository somewhere, I should be able to run actions from it directly without necessarily having to clone the repo manually. The idea is to sort of recreate the magic of  `docker run <image>` where the overhead of playing around with a container image is compressed to a single command, but now applied to the problems `dagger` is tackling. Once I have dagger installed, I should be able to start trying out plans immediately.

There are some obvious security implications to this (don't want a single `dagger` command to expose all your local files and/or env vars to untrusted remote code), so it might not make sense to have this be directly exposed as `dagger do` but instead a different command where local resources are, by default, not available to the actions and instead have to be selectively exposed through flags.

The implementation could probably just reuse Buildkit's support for Git SourceOps (and maybe other source op types too like HTTP and container image), which will take care of a lot of the otherwise hard parts of the implementation (pulling the source, managing state of various sources that have been pulled, isolating sensitive local resources from the remote code, etc.).

_Originally posted by @sipsma in https://github.com/dagger/dagger/discussions/2052#discussioncomment-2548059_

**Comment by shykes** [comment] 2022-04-15 19:11
I agree... I recently felt the need for this. I cloned the cuelang repo, and wanted to build it using my new favorite dev tool: `dagger` :) Really all I wanted was to invoke a standard `go.#Build` action straight from universe, with inputs and outputs passed directly from the command-line.... So I didn't even need a plan. I just wanted to invoke the action directly, in the current context. Not exactly what you described, but probably two facets of the same feature? :)

**Comment by sipsma** [comment] 2022-04-15 22:41
> So I didn't even need a plan. I just wanted to invoke the action directly, in the current context. Not exactly what you described, but probably two facets of the same feature? :)

Yeah good point, this should apply to full plans or just actions. Actions w/out a plan don't have access to any sensitive local resources (I think?), so they don't raise any security questions and are thus probably even easier to support really.

At the end of the day, the issue is that the current state is sort of like being forced to run `curl container.image.registry/... | tar xz` and unpack images manually before calling `docker run`. I guess git repos can operate sort of like dagger's "action registries" in this sense.

**Comment by shykes** [comment] 2022-04-15 23:26
> > So I didn't even need a plan. I just wanted to invoke the action directly, in the current context. Not exactly what you described, but probably two facets of the same feature? :)
> 
> Yeah good point, this should apply to full plans or just actions. Actions w/out a plan don't have access to any sensitive local resources (I think?), so they don't raise any security questions and are thus probably even easier to support really.

Yes that was the overriding priority in the design: strong sandboxing of actions so that they can be safely shared and reused.

> At the end of the day, the issue is that the current state is sort of like being forced to run `curl container.image.registry/... | tar xz` and unpack images manually before calling `docker run`. I guess git repos can operate sort of like dagger's "action registries" in this sense.

Yes I completely agree.

I wonder if a consequence of this, is that plans themselves will become an optional feature: a way to declaratively lay out actions in a certsin way, and give them access to the client in a certain way. Some users would swear by that declarative layer, but others would more casually run individual actions straight from the shell.

You know this is starting to look like `docker` vs `docker-compose` 😁

**Comment by shykes** [comment] 2023-01-03 18:45
Closing this, as it is specific to the CUE version. CLI development is now happening on the new, multi-language version of Dagger.

**Closed by shykes** 2023-01-03 18:45 UTC
Labels: kind/user-request

**Comment by from-nibly** [comment] 2023-01-03 19:56
Is the cue version being deprecated then? I REALLY like using culang to make my builds, it's really what attracted me to this project in the first place.

**Comment by shykes** [comment] 2023-01-03 20:32
> Is the cue version being deprecated then? I REALLY like using culang to make my builds, it's really what attracted me to this project in the first place.

It's not deprecated, but at the moment it's not improving as fast as the other SDKs, because it's stuck on an older version of the Dagger engine *and* an older version of CUE. We invested a lot of effort to port dagger-cue to the new engine and GraphQL API, but that development effort is currently stalled.

We continue to support users of the current SDK, but there is uncertainty on future improvements. It depends in part in how much interest there is from the CUE community and upstream developers.
