### ISSUE TITLE
🐞 `dagger develop --sdk=go` fails if there is a go.mod with go 1.22

### ISSUE THREAD

**Issue by dhowden** [dagger/dagger#7087] opened 2024-04-12 11:43 UTC
### What is the issue?

Running `dagger develop --sdk=go` fails if under a `go.mod` with `go 1.22` (but works with `go 1.22.1`)

https://discord.com/channels/707636530424053791/1227832788825407488/1228123308172640256

### Dagger version

dagger v0.11.0 (registry.dagger.io/engine) darwin/arm64

### Steps to reproduce

```
$ mkdir temp
$ cd temp
$ cat > go.mod << EOF
module example.com/temp

go 1.22
EOF
$ dagger init
$ dagger develop --sdk=go
```

### Log output

```
✘ ModuleSource.asModule: Module! 7.8s
! failed to create module: select: failed to update codegen and runtime: failed to generate code: failed to get modified source directory for go module sdk codegen: select: process "/usr/local/bin/codegen --module-context /src --module-name temp --introspection-json-path /schema.json" did not complete successfully: exit code: 1
  ✘ Module.withSource(
      source: ✔ ModuleSource.resolveFromCaller: ModuleSource! 0.0s
    ): Module! 7.8s
  ! failed to update codegen and runtime: failed to generate code: failed to get modified source directory for go module sdk codegen: select: process "/usr/local/bin/codegen --module-context /src --module-name temp --introspection-json-path /schema.json" did not complete successfully: exit code: 1
    ✘ Container.directory(path: "/src"): Directory! 7.8s
    ! process "/usr/local/bin/codegen --module-context /src --module-name temp --introspection-json-path /schema.json" did not complete successfully: exit code: 1
      ✘ exec /usr/local/bin/codegen --module-context /src --module-name temp --introspection-json-path /schema.json 7.8s
      ! process "/usr/local/bin/codegen --module-context /src --module-name temp --introspection-json-path /schema.json" did not complete successfully: exit code: 1
      ┃ generating go module: temp                                                                                                  
      ┃ Error: generate code: error formatting generated code: err: exit status 1: stderr: go: downloading go1.22 (linux/arm64)     
      ┃ go: download go1.22 for linux/arm64: toolchain not available                                                                
      ┃                                                                                                                             

Error: failed to generate code: input: moduleSource.withContextDirectory.withSDK.withSourceSubpath.asModule resolve: failed to create module: select: failed to update codegen and runtime: failed to generate code: failed to get modified source directory for go module sdk codegen: select: process "/usr/local/bin/codegen --module-context /src --module-name temp --introspection-json-path /schema.json" did not complete successfully: exit code: 1

Stdout:
generating go module: temp
Stderr:
Error: generate code: error formatting generated code: err: exit status 1: stderr: go: downloading go1.22 (linux/arm64)
go: download go1.22 for linux/arm64: toolchain not available
```

**Comment by marcosnils** [comment] 2024-04-12 13:22
looks like a go code generation :bug: . cc @helderco

**Comment by helderco** [comment] 2024-04-12 13:45
@jedevc, can you take a look?

**Comment by jedevc** [comment] 2024-04-15 10:45
See https://github.com/golang/go/issues/62278#issuecomment-1693538776.

I think this is expected - either, the `go` directive should set a minimum patch version, or the `toolchain` directive should be specified. `1.22` isn't a valid toolchain, so when we go to download it, it doesn't exist. You should be able to reproduce this (without dagger at all) by running go version 1.21, and attempting to build a program with a `go.mod` that has `go 1.22`.

The reason you wouldn't see this with 1.21 versions, is that the go version in the dagger image is set to 1.21 - so we never need to download a toolchain for those older versions, that only happens for 1.22. (we *should* update to 1.22, but did encounter some runc issues last time we tried doing it!)

Admittedly, I do think this behavior is kind of weird, but this doesn't seem in-scope for the dagger project - it seems an issue with the go ecosystem in general. I'm going to close this, since I *don't* think this is an issue specific to dagger :cry: (but agreed, very weird).

**Closed by jedevc** 2024-04-15 10:45 UTC
Labels: kind/bug, sdk/go, Modules

**Comment by helderco** [comment] 2024-04-15 11:25
In Python modules now, you can override the default version used in the runtime container. It started as an experiment, but we can either do the same in all SDKs, or not support it. Supporting it means, look for the version in `go.mod` when loading the module (if it exists), and use it to choose the base image for the container.

**Comment by marcosnils** [comment] 2024-04-15 14:07
Thx Justin! I totally missed that the `go.mod` file was missing the patch version and I thought it was just a Dagger issue. Didn't think of trying any go related command to get the same error :pray:
