### ISSUE TITLE
🐞 Directory upload is slow

### ISSUE THREAD

**Issue by ari-becker** [dagger/dagger#5902] opened 2023-10-14 09:52 UTC
### What is the issue?

`client.container().from().withDirectory("/src", client.host().directory("."), { exclude: [ <lots, like node_modules> ] }.withWorkdir("/src").withExec(["/bin/bash", "-ce", "du -sch ; tree -a"]).stdout()`

After adding tons of directories to the exclusion list, this command results in:

* inside the container: `1.7 M` total disk usage, 78 directories, 178 files
* two upload steps: one that takes `58.53s` and one that takes `14.46s`, in serial

Running the commands directly on the host (which has run `pnpm install` etc.): `3.0G` total disk usage, 20728 directories, 72993 files

In my opinion, this is far too long to wait for every run, since changes to the host source files will almost never be cached.

### Steps to reproduce

Unsure how to reproduce.

Original repository is a small Typescript/React/Node monorepo (a side project of mine) with 9 packages.

### SDK version

Node v0.8.8

### OS version

macOS 14.0 on M1/Apple Silicon

**Comment by TomChv** [comment] 2023-10-16 18:34
@ari-becker Did you cached the installation process?

I tried to reproduce this with our own [NodeSDK](https://github.com/dagger/dagger/tree/main/sdk/nodejs), it seems a bit bigger than your typescript repository but it tooks only 10 seconds to upload.

Here's the code I made

```go
package main

import (
	"context"
	"fmt"
	"os"

	"dagger.io/dagger"
)

func main() {
	ctx := context.Background()

	client, err := dagger.Connect(ctx, dagger.WithLogOutput(os.Stderr))
	if err != nil {
		panic(err)
	}

	source := client.Host().Directory("./sdk/nodejs")

	out, err := client.
		Container().
		From("alpine").
		WithDirectory("/src", source, dagger.ContainerWithDirectoryOpts{Exclude: []string{"node_modules"}}).
		WithWorkdir("/src").
		WithExec([]string{"du", "-sch"}).
		WithExec([]string{"tree", "-a"}).
		Stdout(ctx)
	if err != nil {
		panic(err)
	}

	fmt.Println(out)
}
```

The step that upload the folder takes only 10 seconds (constantely)

```shell
▽ │ host.directory ./sdk/nodejs
█ │ [10.12s] upload ./sdk/nodejs
┣ │ [9.92s] transferring eyJvd25lcl9jbGllbnRfaWQiOiJtN2hybWQxamQxenZkdHhmZ3JodjdsN2JnIiwicGF0aCI6InNkay9ub2RlanMiLCJpbmNsdWRlX3BhdHRlcm5zIjpudWxsLCJleGNsdWRlX3BhdHRlcm5zIjpudWxsLCJmb2xsb3dfcGF0aHMiOm51bGwsInJlYWRfc2luZ2xlX2ZpbGVfb25seSI6ZmFsc2UsIm1heF9maWxlX3NpemUiOjB9:
```

I'll also check if it doesn't come from the node version but it shouldn't be the case since upload operation are done on the engine side (which is independant from the SDK used)

If possible, could you share your repository so I can try on it?

**Comment by TomChv** [comment] 2023-10-16 18:47
Same test with the nodeSDK and it's still really fast: less than 7seconds to upload.

```ts
import { connect } from '@dagger.io/dagger';

connect(
	async (client) => {
		const source = client.host().directory('./sdk/nodejs', { exclude: [ 'node_modules' ] });

		const out = await client
			.container()
			.from('alpine')
			.withDirectory('/src', source)
			.withWorkdir("/src")
			.withExec(["du", "-sch"])
			.withExec(["tree", "-a"])
			.stdout()

		console.log(out)

	},
	{ LogOutput: process.stderr });
```

```shell
█ │ [6.44s] upload ./sdk/nodejs
┣ │ [6.39s] transferring eyJvd25lcl9jbGllbnRfaWQiOiJsaWw3cWFhNGUzNzUyMDA2N3R5dzUwMXo2IiwicGF0aCI6InNkay9ub2RlanMiLCJpbmNsdWRlX3BhdHRlcm5zIjpudWxsLCJleGNsdWRlX3BhdHRlcm5zIjpbIm5vZGVfbW9kdWxlcyJdLCJmb2xsb3dfcGF0aHMiOm51bGwsInJlYWRfc2luZ2xlX2ZpbGVfb25seSI6ZmFsc2UsIm1heF9maWxlX3NpemUiOjB9:
```

**Comment by ari-becker** [comment] 2023-10-17 06:34
> Same test with the nodeSDK and it's still really fast: less than 7seconds to upload.
> 
> ```ts
> import { connect } from '@dagger.io/dagger';
> 
> connect(
> 	async (client) => {
> 		const source = client.host().directory('./sdk/nodejs', { exclude: [ 'node_modules' ] });
> 
> 		const out = await client
> 			.container()
> 			.from('alpine')
> 			.withDirectory('/src', source)
> 			.withWorkdir("/src")
> 			.withExec(["du", "-sch"])
> 			.withExec(["tree", "-a"])
> 			.stdout()
> 
> 		console.log(out)
> 
> 	},
> 	{ LogOutput: process.stderr });
> ```
> 
> ```shell
> █ │ [6.44s] upload ./sdk/nodejs
> ┣ │ [6.39s] transferring eyJvd25lcl9jbGllbnRfaWQiOiJsaWw3cWFhNGUzNzUyMDA2N3R5dzUwMXo2IiwicGF0aCI6InNkay9ub2RlanMiLCJpbmNsdWRlX3BhdHRlcm5zIjpudWxsLCJleGNsdWRlX3BhdHRlcm5zIjpbIm5vZGVfbW9kdWxlcyJdLCJmb2xsb3dfcGF0aHMiOm51bGwsInJlYWRfc2luZ2xlX2ZpbGVfb25seSI6ZmFsc2UsIm1heF9maWxlX3NpemUiOjB9:
> ```

@TomChv I can confirm that this runs even quicker on my machine, for the `dagger` repo. With that said, `sdk/nodejs` has a `du -sch` of only `116M`; my argument is that (a) setting exclusions should reduce upload times since those directories do not need to be uploaded, (b) in a large (multi-GB) repository with many exclusions, the time savings from those exclusions are not being realized.

I'll try to repro later on one of the larger public monorepos: https://github.com/korfuri/awesome-monorepo#notable-public-monorepos

**Comment by ari-becker** [comment] 2023-10-18 17:23
> > Maybe there's two sections of code, one that transfers the host directory to buildkit, and one that actually writes files into the container, and the exclude list is improperly handled in the first section but is properly handled in the second section?
> 
> I think it's because your exclude is made after copying the whole directory? Can you try again but instead of doing:
> 
> ```ts
> client
>   .container()
>   .from()
>   .withDirectory("/src", client.host().directory("."), { exclude: [ <lots, like node_modules> ]})
>   ...
> ```
> 
> You try to do
> 
> ```ts
> client
>   .container()
>   .from()
>   .withDirectory("/src", client.host().directory(".", , { exclude: [ <lots, like node_modules> ]}))
>   ...
> ```
> 
> I think you should see a difference in your output

oh wow, yup that did it, now it's done within 170 ms, much better.

@TomChv IMO this is a big footgun in the SDK, it's much too easy to add `exclude` to `container.withDirectory` instead of `host.directory`; TypeScript will accept either usage as valid, and Dagger will silently accept either usage, but with large consequences in large host directories.

Up to you if you think this issue should be closed (because I fixed my problem) or kept open (i.e. as an issue to have an API with less of a footgun?).

**Comment by ari-becker** [comment] 2023-10-18 19:42
![image](https://github.com/dagger/dagger/assets/1388505/175b3e10-ca18-4793-9ee2-1f058c578c54)

also, the [quickstart](https://docs.dagger.io/quickstart/349011/build) unintentionally directs users to use this footgun, which is maybe how I shot myself in the foot in the first place 😅

**Comment by TomChv** [comment] 2023-10-19 06:05
> @TomChv IMO this is a big footgun in the SDK, it's much too easy to add exclude to container.withDirectory instead of host.directory; TypeScript will accept either usage as valid, and Dagger will silently accept either usage, but with large consequences in large host directories.

It actually depends of your use case, if you work from your host filesystem, I totally agree that it can be pretty confusing if you should use `exclude` on `host.Directory()` or `withDirectory()`. However, if you pull a repository or copy a directory from another image's container, then it makes sense to use `withDirectory()`. This is why we actually support both exclusion.

We will work on the documentation to make that clearer. 

> Up to you if you think this issue should be closed (because I fixed my problem) or kept open (i.e. as an issue to have an API with less of a footgun?).
> also, the [quickstart](https://docs.dagger.io/quickstart/349011/build) unintentionally directs users to use this footgun, which is maybe how I shot myself in the foot in the first place 😅

https://github.com/dagger/dagger/pull/5854 is opened to fix that issue. :rocket:

I'm closing this issue, feel free to reopen it if you have another issue with directory upload being slow.

**Closed** 2023-10-19 06:08 UTC
Labels: kind/performance
