### ISSUE TITLE
🐞  Wrong filesystem type leads to dagger hanging

### ISSUE THREAD

**Issue by arnaud-soulie** [dagger/dagger#2026] opened 2022-04-04 14:41 UTC
### What is the issue?

If **contents** is wrongly set to **dagger.#FS** instead of **string** when reading a file from the host filesystem, *dagger do* hangs indefinitely without any error message.

```
dagger.#Plan & {
	client: {
        filesystem: {
            "./app": read: contents: dagger.#FS
            "./manifest": read: contents: dagger.#FS
            "./kubeconfig/config": read: contents: dagger.#FS     //Should be a string here for example
        }

```

### Log output

❯ dagger do deploy -p ci.cue --log-format plain -l debug --no-cache
4:36PM DBG system | detected buildkit config    haveHostNetwork=true isActive=true version=v0.10.0
4:36PM DBG system | spawning buildkit job    attrs=null localdirs={
    "/Users/arnaudsoulie/Programmation/dagger/v2/afterwork/dagger_examples/4/app": "/Users/arnaudsoulie/Programmation/dagger/v2/afterwork/dagger_examples/4/app",
    "/Users/arnaudsoulie/Programmation/dagger/v2/afterwork/dagger_examples/4/kubeconfig/config": "/Users/arnaudsoulie/Programmation/dagger/v2/afterwork/dagger_examples/4/kubeconfig/config",
    "/Users/arnaudsoulie/Programmation/dagger/v2/afterwork/dagger_examples/4/manifest": "/Users/arnaudsoulie/Programmation/dagger/v2/afterwork/dagger_examples/4/manifest"
}

### Steps to reproduce

- Set any filesystem value to point towards a file instead of a folder in the plan
- set *read: contents:* ***dagger.#FS***

### Dagger version

agger 0.2.4 (b32c8732) darwin/amd64

### OS version

macOs 12.1

**Comment by arnaud-soulie** [comment] 2022-04-04 14:42
@grouville

**Comment by grouville** [comment] 2022-04-04 14:43
cc @helderco

**Comment by marcosnils** [comment] 2022-04-04 14:43
hey @arnaud-soulie! thx for reporting this. It has been recently fixed by https://github.com/dagger/dagger/pull/1979. It will land in the next release.

**Comment by marcosnils** [comment] 2022-04-04 14:44
Closing as dupe of #1977

**Closed by marcosnils** 2022-04-04 14:44 UTC
